/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.SysLevelDAO;

import com.onway.fyapp.common.dal.dataobject.SysLevelDO;
import java.util.List;
import org.springframework.dao.DataAccessException;

import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.SysLevelDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_level.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisSysLevelDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisSysLevelDAO extends SqlMapClientDaoSupport implements SysLevelDAO {
	/**
	 *  Query DB table <tt>sys_level</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_level</tt>
	 *
	 *	@param level
	 *	@param type
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<SysLevelDO>
	 *	@throws DataAccessException
	 */	 
    public  List<SysLevelDO>   searchAllLevel(String level, String type, Integer startRow, Integer pageSize) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("level", level);
        param.put("type", type);
        param.put("startRow", startRow);
        param.put("pageSize", pageSize);

        return getSqlMapClientTemplate().queryForList("MS-SYS-LEVEL-SEARCH-ALL-LEVEL", param);

    }

	/**
	 *  Query DB table <tt>sys_level</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from sys_level</tt>
	 *
	 *	@param level
	 *	@param type
	 *	@param startRow
	 *	@param pageSize
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   searchAllLevelCount(String level, String type, Integer startRow, Integer pageSize) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("level", level);
        param.put("type", type);
        param.put("startRow", startRow);
        param.put("pageSize", pageSize);

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-SYS-LEVEL-SEARCH-ALL-LEVEL-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Insert one <tt>SysLevelDO</tt> object to DB table <tt>sys_level</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sys_level(LEVEL_TYPE,MIN_AMOUNT,MAX_AMOUNT,TYPE,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param sysLevel
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   newLevelInfo(SysLevelDO sysLevel) throws DataAccessException {
    	if (sysLevel == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-SYS-LEVEL-NEW-LEVEL-INFO", sysLevel);

        return sysLevel.getId();
    }

	/**
	 *  Update DB table <tt>sys_level</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sys_level set MIN_AMOUNT=?, MAX_AMOUNT=?, DICOUNT_RATE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ID = ?)</tt>
	 *
	 *	@param sysLevel
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updateLevelInfo(SysLevelDO sysLevel) throws DataAccessException {
    	if (sysLevel == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-SYS-LEVEL-UPDATE-LEVEL-INFO", sysLevel);
    }

	/**
	 *  Delete records from DB table <tt>sys_level</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sys_level where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   deleteLevelInfo(int id) throws DataAccessException {
        Integer param = new Integer(id);

        return getSqlMapClientTemplate().delete("MS-SYS-LEVEL-DELETE-LEVEL-INFO", param);
    }

	/**
	 *  Query DB table <tt>sys_level</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_level</tt>
	 *
	 *	@param type
	 *	@param levelType
	 *	@return SysLevelDO
	 *	@throws DataAccessException
	 */	 
    public  SysLevelDO   just(String type, String levelType) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("type", type);
        param.put("levelType", levelType);

	        return (SysLevelDO) getSqlMapClientTemplate().queryForObject("MS-SYS-LEVEL-JUST", param);
		
    }

	/**
	 *  Query DB table <tt>sys_level</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_level</tt>
	 *
	 *	@param levelType
	 *	@param type
	 *	@return SysLevelDO
	 *	@throws DataAccessException
	 */	 
    public  SysLevelDO   query(String levelType, String type) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("levelType", levelType);
        param.put("type", type);

	        return (SysLevelDO) getSqlMapClientTemplate().queryForObject("MS-SYS-LEVEL-QUERY", param);
		
    }

}