/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.DiscountDAO;

import java.util.Date;
import com.onway.fyapp.common.dal.dataobject.DiscountDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import com.onway.common.lang.Money;
import java.util.HashMap;

import java.util.Map;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.DiscountDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_discount.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisDiscountDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisDiscountDAO extends SqlMapClientDaoSupport implements DiscountDAO {
	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@param discountName
	 *	@param discountType
	 *	@param teamId
	 *	@param teamName
	 *	@param teamErpNo
	 *	@param productId
	 *	@param productIdArray
	 *	@param speType
	 *	@param canOverUse
	 *	@param limitUserLevel
	 *	@param startDate
	 *	@param endDate
	 *	@param thisDate
	 *	@param thisDiscounId
	 *	@param publishFlg
	 *	@param teamChildId
	 *	@param teamChildIdArray
	 *	@param linkCityArray
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   queryList(String discountId, String discountName, String discountType, String teamId, String teamName, String teamErpNo, String productId, String productIdArray, String speType, String canOverUse, String limitUserLevel, Date startDate, Date endDate, Date thisDate, String thisDiscounId, String publishFlg, String teamChildId, String teamChildIdArray, String linkCityArray, String offset, String limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("teamId", teamId);
        param.put("teamName", teamName);
        param.put("teamErpNo", teamErpNo);
        param.put("productId", productId);
        param.put("productIdArray", productIdArray);
        param.put("speType", speType);
        param.put("canOverUse", canOverUse);
        param.put("limitUserLevel", limitUserLevel);
        param.put("startDate", startDate);
        param.put("endDate", endDate);
        param.put("thisDate", thisDate);
        param.put("thisDiscounId", thisDiscounId);
        param.put("publishFlg", publishFlg);
        param.put("teamChildId", teamChildId);
        param.put("teamChildIdArray", teamChildIdArray);
        param.put("linkCityArray", linkCityArray);
        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-DISCOUNT-QUERY-LIST", param);

    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@param discountName
	 *	@param discountType
	 *	@param teamId
	 *	@param teamName
	 *	@param teamErpNo
	 *	@param productId
	 *	@param productIdArray
	 *	@param speType
	 *	@param canOverUse
	 *	@param limitUserLevel
	 *	@param startDate
	 *	@param endDate
	 *	@param thisDate
	 *	@param thisDiscounId
	 *	@param publishFlg
	 *	@param teamChildId
	 *	@param teamChildIdArray
	 *	@param linkCityArray
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   queryListCount(String discountId, String discountName, String discountType, String teamId, String teamName, String teamErpNo, String productId, String productIdArray, String speType, String canOverUse, String limitUserLevel, Date startDate, Date endDate, Date thisDate, String thisDiscounId, String publishFlg, String teamChildId, String teamChildIdArray, String linkCityArray) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("teamId", teamId);
        param.put("teamName", teamName);
        param.put("teamErpNo", teamErpNo);
        param.put("productId", productId);
        param.put("productIdArray", productIdArray);
        param.put("speType", speType);
        param.put("canOverUse", canOverUse);
        param.put("limitUserLevel", limitUserLevel);
        param.put("startDate", startDate);
        param.put("endDate", endDate);
        param.put("thisDate", thisDate);
        param.put("thisDiscounId", thisDiscounId);
        param.put("publishFlg", publishFlg);
        param.put("teamChildId", teamChildId);
        param.put("teamChildIdArray", teamChildIdArray);
        param.put("linkCityArray", linkCityArray);

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-QUERY-LIST-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_discount</tt>
	 *
	 *	@param discountTeamId
	 *	@param discountName
	 *	@param discountType
	 *	@param discountId
	 *	@param offset
	 *	@param limit
	 *	@return List<DiscountDO>
	 *	@throws DataAccessException
	 */	 
    public  List<DiscountDO>   queryGroupList(String discountTeamId, String discountName, String discountType, String discountId, String offset, String limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountTeamId", discountTeamId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("discountId", discountId);
        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-DISCOUNT-QUERY-GROUP-LIST", param);

    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_discount</tt>
	 *
	 *	@param discountTeamId
	 *	@param discountName
	 *	@param discountType
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   queryGroupListCount(String discountTeamId, String discountName, String discountType, String discountId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountTeamId", discountTeamId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("discountId", discountId);

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-QUERY-GROUP-LIST-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@param discountName
	 *	@param discountType
	 *	@param speType
	 *	@param thisDate
	 *	@param offset
	 *	@param limit
	 *	@return List<DiscountDO>
	 *	@throws DataAccessException
	 */	 
    public  List<DiscountDO>   queryListForAlert(String discountId, String discountName, String discountType, String speType, Date thisDate, String offset, String limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("speType", speType);
        param.put("thisDate", thisDate);
        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-DISCOUNT-QUERY-LIST-FOR-ALERT", param);

    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@param discountName
	 *	@param discountType
	 *	@param speType
	 *	@param thisDate
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   queryListForAlertCount(String discountId, String discountName, String discountType, String speType, Date thisDate) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("speType", speType);
        param.put("thisDate", thisDate);

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-QUERY-LIST-FOR-ALERT-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Insert one <tt>DiscountDO</tt> object to DB table <tt>hqyt_discount</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into hqyt_discount(DISCOUNT_TEAM_ID,DISCOUNT_ID,DISCOUNT_NAME,DISCOUNT_TYPE,DISCOUNT_BACKGROUND,AMOUNT,LIMIT_AMOUNT,DISCOUNT,TIME_TYPE,TIME_END,TIME_END_RECEIVE,LINK_TEAM,LINK_PRO,DISCOUNT_SUB_TYPE,CAN_OVER_USE,CAN_OVER_NUMS,CAN_TOGE_USE,CAN_TOGE_DISID,LIMIT_USER_LEVEL,DEL_FLG,RANK,CAN_DISCOUNT_USE,CREATER,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param discount
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insert(DiscountDO discount) throws DataAccessException {
    	if (discount == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-DISCOUNT-INSERT", discount);

        return discount.getId();
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set DISCOUNT_TEAM_ID=?, DISCOUNT_NAME=?, DISCOUNT_TYPE=?, DISCOUNT_BACKGROUND=?, AMOUNT=?, LIMIT_AMOUNT=?, DISCOUNT=?, TIME_TYPE=?, TIME_END=?, TIME_END_RECEIVE=?, LINK_TEAM=?, LINK_PRO=?, DISCOUNT_SUB_TYPE=?, CAN_OVER_USE=?, CAN_OVER_NUMS=?, CAN_TOGE_USE=?, CAN_TOGE_DISID=?, LIMIT_USER_LEVEL=?, RANK=?, DEL_FLG=?, MODIFIER=?, CAN_DISCOUNT_USE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param discountTeamId
	 *	@param discountName
	 *	@param discountType
	 *	@param discountBackground
	 *	@param amount
	 *	@param limitAmount
	 *	@param discount
	 *	@param timeType
	 *	@param timeEnd
	 *	@param timeEndReceive
	 *	@param linkTeam
	 *	@param linkPro
	 *	@param discountSubType
	 *	@param canOverUse
	 *	@param canOverNums
	 *	@param canTogeUse
	 *	@param canTogeDisid
	 *	@param limitUserLevel
	 *	@param rank
	 *	@param delFlg
	 *	@param modifier
	 *	@param canDiscountUse
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   update(String discountTeamId, String discountName, String discountType, String discountBackground, Money amount, Money limitAmount, double discount, String timeType, String timeEnd, Date timeEndReceive, String linkTeam, String linkPro, String discountSubType, String canOverUse, int canOverNums, String canTogeUse, String canTogeDisid, int limitUserLevel, int rank, String delFlg, String modifier, String canDiscountUse, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountTeamId", discountTeamId);
        param.put("discountName", discountName);
        param.put("discountType", discountType);
        param.put("discountBackground", discountBackground);
        param.put("amount", amount);
        param.put("limitAmount", limitAmount);
        param.put("discount", new Double(discount));
        param.put("timeType", timeType);
        param.put("timeEnd", timeEnd);
        param.put("timeEndReceive", timeEndReceive);
        param.put("linkTeam", linkTeam);
        param.put("linkPro", linkPro);
        param.put("discountSubType", discountSubType);
        param.put("canOverUse", canOverUse);
        param.put("canOverNums", new Integer(canOverNums));
        param.put("canTogeUse", canTogeUse);
        param.put("canTogeDisid", canTogeDisid);
        param.put("limitUserLevel", new Integer(limitUserLevel));
        param.put("rank", new Integer(rank));
        param.put("delFlg", delFlg);
        param.put("modifier", modifier);
        param.put("canDiscountUse", canDiscountUse);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-UPDATE", param);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set DEL_FLG='1', MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   delete(String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-DELETE", param);
    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from hqyt_discount where ((DISCOUNT_TEAM_ID = ?) AND (DEL_FLG NOT IN ('1')) AND (PUBLISH_FLG = '1'))</tt>
	 *
	 *	@param discountTeamId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   queryCountDiscount(String discountTeamId) throws DataAccessException {

 
	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-QUERY-COUNT-DISCOUNT", discountTeamId);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set DISCOUNT_TEAM_ID=NULL, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   removeDiscount(String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-REMOVE-DISCOUNT", param);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set CAN_TOGE_USE=?, CAN_TOGE_DISID=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param canTogeUse
	 *	@param canTogeDisid
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updateCanTogetherDiscounId(String canTogeUse, String canTogeDisid, String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("canTogeUse", canTogeUse);
        param.put("canTogeDisid", canTogeDisid);
        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-UPDATE-CAN-TOGETHER-DISCOUN-ID", param);
    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@return DiscountDO
	 *	@throws DataAccessException
	 */	 
    public  DiscountDO   queryByDiscountId(String discountId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);

	        return (DiscountDO) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-QUERY-BY-DISCOUNT-ID", param);
		
    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@return List<DiscountDO>
	 *	@throws DataAccessException
	 */	 
    public  List<DiscountDO>   queryByCantogeId(String discountId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);

        return getSqlMapClientTemplate().queryForList("MS-DISCOUNT-QUERY-BY-CANTOGE-ID", param);

    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set LINK_PRO=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param linkPro
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   modifyLinkPro(String linkPro, String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("linkPro", linkPro);
        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-MODIFY-LINK-PRO", param);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set LINK_TEAM=?, LINK_TEAM_CHILD=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param discount
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   modifyLinkTeam(DiscountDO discount) throws DataAccessException {
    	if (discount == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-DISCOUNT-MODIFY-LINK-TEAM", discount);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set CAN_TOGE_DISID=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param canTogeDisid
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   modifyLinkDis(String canTogeDisid, String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("canTogeDisid", canTogeDisid);
        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-MODIFY-LINK-DIS", param);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set LINK_TEAM_CHILD=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param linkTeamChild
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   modifyLinkTeamChild(String linkTeamChild, String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("linkTeamChild", linkTeamChild);
        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-MODIFY-LINK-TEAM-CHILD", param);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set PUBLISH_FLG=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param publishFlg
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   modifyPublishFlg(String publishFlg, String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("publishFlg", publishFlg);
        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-MODIFY-PUBLISH-FLG", param);
    }

	/**
	 *  Update DB table <tt>hqyt_discount</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_discount set LINK_PROVINCE=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (DISCOUNT_ID = ?)</tt>
	 *
	 *	@param linkProvince
	 *	@param modifier
	 *	@param discountId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   modifyLinkProvince(String linkProvince, String modifier, String discountId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("linkProvince", linkProvince);
        param.put("modifier", modifier);
        param.put("discountId", discountId);

        return getSqlMapClientTemplate().update("MS-DISCOUNT-MODIFY-LINK-PROVINCE", param);
    }

	/**
	 *  Query DB table <tt>hqyt_discount</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select DISCOUNT_NAME from hqyt_discount</tt>
	 *
	 *	@param discountId
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public  String   getDisCountName(String discountId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("discountId", discountId);

	        return (String) getSqlMapClientTemplate().queryForObject("MS-DISCOUNT-GET-DIS-COUNT-NAME", param);
		
    }

}