/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.SysExpressDAO;

import com.onway.fyapp.common.dal.dataobject.SysExpressDO;
import java.util.List;
import org.springframework.dao.DataAccessException;

import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.SysExpressDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_express.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisSysExpressDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisSysExpressDAO extends SqlMapClientDaoSupport implements SysExpressDAO {
	/**
	 *  Query DB table <tt>sys_express</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, EXPRESS_NO, COM, EXPRESS_NAME, SORT_NUM, STATUS, GMT_CREATE, GMT_MODIFIED from sys_express where (STATUS = 'ENABLE') order by SORT_NUM ASC</tt>
	 *
	 *	@return List<SysExpressDO>
	 *	@throws DataAccessException
	 */	 
    public  List<SysExpressDO>   selectAll() throws DataAccessException {


        return getSqlMapClientTemplate().queryForList("MS-SYS-EXPRESS-SELECT-ALL", null);

    }

	/**
	 *  Query DB table <tt>sys_express</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, EXPRESS_NO, COM, EXPRESS_NAME, SORT_NUM, STATUS, GMT_CREATE, GMT_MODIFIED from sys_express where (EXPRESS_NO = ?)</tt>
	 *
	 *	@param expressNo
	 *	@return SysExpressDO
	 *	@throws DataAccessException
	 */	 
    public  SysExpressDO   selectByExpressNo(String expressNo) throws DataAccessException {

 
	        return (SysExpressDO) getSqlMapClientTemplate().queryForObject("MS-SYS-EXPRESS-SELECT-BY-EXPRESS-NO", expressNo);
		
    }

	/**
	 *  Query DB table <tt>sys_express</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, EXPRESS_NO, COM, EXPRESS_NAME, SORT_NUM, STATUS, GMT_CREATE, GMT_MODIFIED from sys_express where (COM = ?)</tt>
	 *
	 *	@param com
	 *	@return SysExpressDO
	 *	@throws DataAccessException
	 */	 
    public  SysExpressDO   selectByCom(String com) throws DataAccessException {

 
	        return (SysExpressDO) getSqlMapClientTemplate().queryForObject("MS-SYS-EXPRESS-SELECT-BY-COM", com);
		
    }

}