/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.InvoiceDAO;

import com.onway.fyapp.common.dal.dataobject.InvoiceDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import com.onway.fyapp.common.dal.dataobject.rst.InvoiceResult;

import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.InvoiceDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_invoice.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisInvoiceDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisInvoiceDAO extends SqlMapClientDaoSupport implements InvoiceDAO {
	/**
	 *  Query DB table <tt>hqyt_invoice</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_invoice where (1 = 1)</tt>
	 *
	 *	@param cell
	 *	@param nickName
	 *	@param invoiceid
	 *	@param printStatus
	 *	@param orderid
	 *	@param offset
	 *	@param limit
	 *	@return List<InvoiceResult>
	 *	@throws DataAccessException
	 */	 
    public  List<InvoiceResult>   selectinvoice(String cell, String nickName, String invoiceid, String printStatus, String orderid, Integer offset, Integer limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("cell", cell);
        param.put("nickName", nickName);
        param.put("invoiceid", invoiceid);
        param.put("printStatus", printStatus);
        param.put("orderid", orderid);
        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-INVOICE-SELECTINVOICE", param);

    }

	/**
	 *  Update DB table <tt>hqyt_invoice</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_invoice set PRINT_STATUS=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ID = ?)</tt>
	 *
	 *	@param printStatus
	 *	@param modifier
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updatePrintStatus(String printStatus, String modifier, int id) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("printStatus", printStatus);
        param.put("modifier", modifier);
        param.put("id", new Integer(id));

        return getSqlMapClientTemplate().update("MS-INVOICE-UPDATE-PRINT-STATUS", param);
    }

}