/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.SysZjmDAO;

import com.onway.fyapp.common.dal.dataobject.SysZjmDO;
import org.springframework.dao.DataAccessException;

import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.SysZjmDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_zjm.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisSysZjmDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisSysZjmDAO extends SqlMapClientDaoSupport implements SysZjmDAO {
	/**
	 *  Query DB table <tt>sys_zjm</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_zjm</tt>
	 *
	 *	@param sourceStr
	 *	@return SysZjmDO
	 *	@throws DataAccessException
	 */	 
    public  SysZjmDO   getZjm(String sourceStr) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("sourceStr", sourceStr);

	        return (SysZjmDO) getSqlMapClientTemplate().queryForObject("MS-SYS-ZJM-GET-ZJM", param);
		
    }

}