/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;
import com.onway.common.lang.Money;

/**
 * A data object class directly models database table <tt>hqyt_account_temp</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_account_temp.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: AccountTempDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class AccountTempDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>LINK_ID</tt>.
	 */
	private String linkId;

	/**
	 * This property corresponds to db column <tt>TYPE</tt>.
	 */
	private String type;

	/**
	 * This property corresponds to db column <tt>TEMP_TYPE</tt>.
	 */
	private String tempType;

	/**
	 * This property corresponds to db column <tt>AMOUNT</tt>.
	 */
	private Money amount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>START_DATE</tt>.
	 */
	private Date startDate;

	/**
	 * This property corresponds to db column <tt>END_DATE</tt>.
	 */
	private Date endDate;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>linkId</tt>.
     *
     * @return property value of linkId
     */
	public String getLinkId() {
		return linkId;
	}
	
	/**
	 * Setter method for property <tt>linkId</tt>.
	 * 
	 * @param linkId value to be assigned to property linkId
     */
	public void setLinkId(String linkId) {
		this.linkId = linkId;
	}

    /**
     * Getter method for property <tt>type</tt>.
     *
     * @return property value of type
     */
	public String getType() {
		return type;
	}
	
	/**
	 * Setter method for property <tt>type</tt>.
	 * 
	 * @param type value to be assigned to property type
     */
	public void setType(String type) {
		this.type = type;
	}

    /**
     * Getter method for property <tt>tempType</tt>.
     *
     * @return property value of tempType
     */
	public String getTempType() {
		return tempType;
	}
	
	/**
	 * Setter method for property <tt>tempType</tt>.
	 * 
	 * @param tempType value to be assigned to property tempType
     */
	public void setTempType(String tempType) {
		this.tempType = tempType;
	}

    /**
     * Getter method for property <tt>amount</tt>.
     *
     * @return property value of amount
     */
	public Money getAmount() {
		return amount;
	}
	
	/**
	 * Setter method for property <tt>amount</tt>.
	 * 
	 * @param amount value to be assigned to property amount
     */
	public void setAmount(Money amount) {
		if (amount == null) {
			this.amount = new Money(0, 0);
		} else {
			this.amount = amount;
		}
	}

    /**
     * Getter method for property <tt>startDate</tt>.
     *
     * @return property value of startDate
     */
	public Date getStartDate() {
		return startDate;
	}
	
	/**
	 * Setter method for property <tt>startDate</tt>.
	 * 
	 * @param startDate value to be assigned to property startDate
     */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

    /**
     * Getter method for property <tt>endDate</tt>.
     *
     * @return property value of endDate
     */
	public Date getEndDate() {
		return endDate;
	}
	
	/**
	 * Setter method for property <tt>endDate</tt>.
	 * 
	 * @param endDate value to be assigned to property endDate
     */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
