/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_address</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_address.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: AddressDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class AddressDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>IS_DEFALT</tt>.
	 */
	private String isDefalt;

	/**
	 * This property corresponds to db column <tt>RE_USER_NAME</tt>.
	 */
	private String reUserName;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>PROVINCE</tt>.
	 */
	private String province;

	/**
	 * This property corresponds to db column <tt>CITY</tt>.
	 */
	private String city;

	/**
	 * This property corresponds to db column <tt>AREA</tt>.
	 */
	private String area;

	/**
	 * This property corresponds to db column <tt>RE_ADDR</tt>.
	 */
	private String reAddr;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>isDefalt</tt>.
     *
     * @return property value of isDefalt
     */
	public String getIsDefalt() {
		return isDefalt;
	}
	
	/**
	 * Setter method for property <tt>isDefalt</tt>.
	 * 
	 * @param isDefalt value to be assigned to property isDefalt
     */
	public void setIsDefalt(String isDefalt) {
		this.isDefalt = isDefalt;
	}

    /**
     * Getter method for property <tt>reUserName</tt>.
     *
     * @return property value of reUserName
     */
	public String getReUserName() {
		return reUserName;
	}
	
	/**
	 * Setter method for property <tt>reUserName</tt>.
	 * 
	 * @param reUserName value to be assigned to property reUserName
     */
	public void setReUserName(String reUserName) {
		this.reUserName = reUserName;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>province</tt>.
     *
     * @return property value of province
     */
	public String getProvince() {
		return province;
	}
	
	/**
	 * Setter method for property <tt>province</tt>.
	 * 
	 * @param province value to be assigned to property province
     */
	public void setProvince(String province) {
		this.province = province;
	}

    /**
     * Getter method for property <tt>city</tt>.
     *
     * @return property value of city
     */
	public String getCity() {
		return city;
	}
	
	/**
	 * Setter method for property <tt>city</tt>.
	 * 
	 * @param city value to be assigned to property city
     */
	public void setCity(String city) {
		this.city = city;
	}

    /**
     * Getter method for property <tt>area</tt>.
     *
     * @return property value of area
     */
	public String getArea() {
		return area;
	}
	
	/**
	 * Setter method for property <tt>area</tt>.
	 * 
	 * @param area value to be assigned to property area
     */
	public void setArea(String area) {
		this.area = area;
	}

    /**
     * Getter method for property <tt>reAddr</tt>.
     *
     * @return property value of reAddr
     */
	public String getReAddr() {
		return reAddr;
	}
	
	/**
	 * Setter method for property <tt>reAddr</tt>.
	 * 
	 * @param reAddr value to be assigned to property reAddr
     */
	public void setReAddr(String reAddr) {
		this.reAddr = reAddr;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
