/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_banner</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_banner.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: BannerDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class BannerDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>BANNER_TYPE</tt>.
	 */
	private String bannerType;

	/**
	 * This property corresponds to db column <tt>BANNER_IMG</tt>.
	 */
	private String bannerImg;

	/**
	 * This property corresponds to db column <tt>BANNER_DESC</tt>.
	 */
	private String bannerDesc;

	/**
	 * This property corresponds to db column <tt>BANNER_CONTENT</tt>.
	 */
	private String bannerContent;

	/**
	 * This property corresponds to db column <tt>BANNER_POSITION</tt>.
	 */
	private String bannerPosition;

	/**
	 * This property corresponds to db column <tt>RANK</tt>.
	 */
	private int rank;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>bannerType</tt>.
     *
     * @return property value of bannerType
     */
	public String getBannerType() {
		return bannerType;
	}
	
	/**
	 * Setter method for property <tt>bannerType</tt>.
	 * 
	 * @param bannerType value to be assigned to property bannerType
     */
	public void setBannerType(String bannerType) {
		this.bannerType = bannerType;
	}

    /**
     * Getter method for property <tt>bannerImg</tt>.
     *
     * @return property value of bannerImg
     */
	public String getBannerImg() {
		return bannerImg;
	}
	
	/**
	 * Setter method for property <tt>bannerImg</tt>.
	 * 
	 * @param bannerImg value to be assigned to property bannerImg
     */
	public void setBannerImg(String bannerImg) {
		this.bannerImg = bannerImg;
	}

    /**
     * Getter method for property <tt>bannerDesc</tt>.
     *
     * @return property value of bannerDesc
     */
	public String getBannerDesc() {
		return bannerDesc;
	}
	
	/**
	 * Setter method for property <tt>bannerDesc</tt>.
	 * 
	 * @param bannerDesc value to be assigned to property bannerDesc
     */
	public void setBannerDesc(String bannerDesc) {
		this.bannerDesc = bannerDesc;
	}

    /**
     * Getter method for property <tt>bannerContent</tt>.
     *
     * @return property value of bannerContent
     */
	public String getBannerContent() {
		return bannerContent;
	}
	
	/**
	 * Setter method for property <tt>bannerContent</tt>.
	 * 
	 * @param bannerContent value to be assigned to property bannerContent
     */
	public void setBannerContent(String bannerContent) {
		this.bannerContent = bannerContent;
	}

    /**
     * Getter method for property <tt>bannerPosition</tt>.
     *
     * @return property value of bannerPosition
     */
	public String getBannerPosition() {
		return bannerPosition;
	}
	
	/**
	 * Setter method for property <tt>bannerPosition</tt>.
	 * 
	 * @param bannerPosition value to be assigned to property bannerPosition
     */
	public void setBannerPosition(String bannerPosition) {
		this.bannerPosition = bannerPosition;
	}

    /**
     * Getter method for property <tt>rank</tt>.
     *
     * @return property value of rank
     */
	public int getRank() {
		return rank;
	}
	
	/**
	 * Setter method for property <tt>rank</tt>.
	 * 
	 * @param rank value to be assigned to property rank
     */
	public void setRank(int rank) {
		this.rank = rank;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
}
