/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_discount_team</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_discount_team.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: DiscountTeamDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class DiscountTeamDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>DISCOUNT_TEAM_ID</tt>.
	 */
	private String discountTeamId;

	/**
	 * This property corresponds to db column <tt>DISCOUNT_TITLE</tt>.
	 */
	private String discountTitle;

	/**
	 * This property corresponds to db column <tt>DISCOUNT_DESC</tt>.
	 */
	private String discountDesc;

	/**
	 * This property corresponds to db column <tt>TITLE_COLOR</tt>.
	 */
	private String titleColor;

	/**
	 * This property corresponds to db column <tt>DESC_COLOR</tt>.
	 */
	private String descColor;

	/**
	 * This property corresponds to db column <tt>DISCOUNT_BACKGROUND</tt>.
	 */
	private String discountBackground;

	/**
	 * This property corresponds to db column <tt>DISCOUNT_BACKGROUND_PC</tt>.
	 */
	private String discountBackgroundPc;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>discountTeamId</tt>.
     *
     * @return property value of discountTeamId
     */
	public String getDiscountTeamId() {
		return discountTeamId;
	}
	
	/**
	 * Setter method for property <tt>discountTeamId</tt>.
	 * 
	 * @param discountTeamId value to be assigned to property discountTeamId
     */
	public void setDiscountTeamId(String discountTeamId) {
		this.discountTeamId = discountTeamId;
	}

    /**
     * Getter method for property <tt>discountTitle</tt>.
     *
     * @return property value of discountTitle
     */
	public String getDiscountTitle() {
		return discountTitle;
	}
	
	/**
	 * Setter method for property <tt>discountTitle</tt>.
	 * 
	 * @param discountTitle value to be assigned to property discountTitle
     */
	public void setDiscountTitle(String discountTitle) {
		this.discountTitle = discountTitle;
	}

    /**
     * Getter method for property <tt>discountDesc</tt>.
     *
     * @return property value of discountDesc
     */
	public String getDiscountDesc() {
		return discountDesc;
	}
	
	/**
	 * Setter method for property <tt>discountDesc</tt>.
	 * 
	 * @param discountDesc value to be assigned to property discountDesc
     */
	public void setDiscountDesc(String discountDesc) {
		this.discountDesc = discountDesc;
	}

    /**
     * Getter method for property <tt>titleColor</tt>.
     *
     * @return property value of titleColor
     */
	public String getTitleColor() {
		return titleColor;
	}
	
	/**
	 * Setter method for property <tt>titleColor</tt>.
	 * 
	 * @param titleColor value to be assigned to property titleColor
     */
	public void setTitleColor(String titleColor) {
		this.titleColor = titleColor;
	}

    /**
     * Getter method for property <tt>descColor</tt>.
     *
     * @return property value of descColor
     */
	public String getDescColor() {
		return descColor;
	}
	
	/**
	 * Setter method for property <tt>descColor</tt>.
	 * 
	 * @param descColor value to be assigned to property descColor
     */
	public void setDescColor(String descColor) {
		this.descColor = descColor;
	}

    /**
     * Getter method for property <tt>discountBackground</tt>.
     *
     * @return property value of discountBackground
     */
	public String getDiscountBackground() {
		return discountBackground;
	}
	
	/**
	 * Setter method for property <tt>discountBackground</tt>.
	 * 
	 * @param discountBackground value to be assigned to property discountBackground
     */
	public void setDiscountBackground(String discountBackground) {
		this.discountBackground = discountBackground;
	}

    /**
     * Getter method for property <tt>discountBackgroundPc</tt>.
     *
     * @return property value of discountBackgroundPc
     */
	public String getDiscountBackgroundPc() {
		return discountBackgroundPc;
	}
	
	/**
	 * Setter method for property <tt>discountBackgroundPc</tt>.
	 * 
	 * @param discountBackgroundPc value to be assigned to property discountBackgroundPc
     */
	public void setDiscountBackgroundPc(String discountBackgroundPc) {
		this.discountBackgroundPc = discountBackgroundPc;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
}
