/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_img</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_img.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ImgDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class ImgDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>IMG_ID</tt>.
	 */
	private String imgId;

	/**
	 * This property corresponds to db column <tt>IMG_TYPE</tt>.
	 */
	private String imgType;

	/**
	 * This property corresponds to db column <tt>IMG_FLG</tt>.
	 */
	private String imgFlg;

	/**
	 * This property corresponds to db column <tt>IMG_URL</tt>.
	 */
	private String imgUrl;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>imgId</tt>.
     *
     * @return property value of imgId
     */
	public String getImgId() {
		return imgId;
	}
	
	/**
	 * Setter method for property <tt>imgId</tt>.
	 * 
	 * @param imgId value to be assigned to property imgId
     */
	public void setImgId(String imgId) {
		this.imgId = imgId;
	}

    /**
     * Getter method for property <tt>imgType</tt>.
     *
     * @return property value of imgType
     */
	public String getImgType() {
		return imgType;
	}
	
	/**
	 * Setter method for property <tt>imgType</tt>.
	 * 
	 * @param imgType value to be assigned to property imgType
     */
	public void setImgType(String imgType) {
		this.imgType = imgType;
	}

    /**
     * Getter method for property <tt>imgFlg</tt>.
     *
     * @return property value of imgFlg
     */
	public String getImgFlg() {
		return imgFlg;
	}
	
	/**
	 * Setter method for property <tt>imgFlg</tt>.
	 * 
	 * @param imgFlg value to be assigned to property imgFlg
     */
	public void setImgFlg(String imgFlg) {
		this.imgFlg = imgFlg;
	}

    /**
     * Getter method for property <tt>imgUrl</tt>.
     *
     * @return property value of imgUrl
     */
	public String getImgUrl() {
		return imgUrl;
	}
	
	/**
	 * Setter method for property <tt>imgUrl</tt>.
	 * 
	 * @param imgUrl value to be assigned to property imgUrl
     */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
