/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_invoice</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_invoice.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: InvoiceDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class InvoiceDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>INVOICE_NO</tt>.
	 */
	private String invoiceNo;

	/**
	 * This property corresponds to db column <tt>TYPE</tt>.
	 */
	private String type;

	/**
	 * This property corresponds to db column <tt>INVOICE_TITLE</tt>.
	 */
	private String invoiceTitle;

	/**
	 * This property corresponds to db column <tt>TAX_NUMBER</tt>.
	 */
	private String taxNumber;

	/**
	 * This property corresponds to db column <tt>INVOICE_CONTENT</tt>.
	 */
	private String invoiceContent;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>PRINT_STATUS</tt>.
	 */
	private String printStatus;

	/**
	 * This property corresponds to db column <tt>COM_BANK</tt>.
	 */
	private String comBank;

	/**
	 * This property corresponds to db column <tt>COM_ADDRESS</tt>.
	 */
	private String comAddress;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>invoiceNo</tt>.
     *
     * @return property value of invoiceNo
     */
	public String getInvoiceNo() {
		return invoiceNo;
	}
	
	/**
	 * Setter method for property <tt>invoiceNo</tt>.
	 * 
	 * @param invoiceNo value to be assigned to property invoiceNo
     */
	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

    /**
     * Getter method for property <tt>type</tt>.
     *
     * @return property value of type
     */
	public String getType() {
		return type;
	}
	
	/**
	 * Setter method for property <tt>type</tt>.
	 * 
	 * @param type value to be assigned to property type
     */
	public void setType(String type) {
		this.type = type;
	}

    /**
     * Getter method for property <tt>invoiceTitle</tt>.
     *
     * @return property value of invoiceTitle
     */
	public String getInvoiceTitle() {
		return invoiceTitle;
	}
	
	/**
	 * Setter method for property <tt>invoiceTitle</tt>.
	 * 
	 * @param invoiceTitle value to be assigned to property invoiceTitle
     */
	public void setInvoiceTitle(String invoiceTitle) {
		this.invoiceTitle = invoiceTitle;
	}

    /**
     * Getter method for property <tt>taxNumber</tt>.
     *
     * @return property value of taxNumber
     */
	public String getTaxNumber() {
		return taxNumber;
	}
	
	/**
	 * Setter method for property <tt>taxNumber</tt>.
	 * 
	 * @param taxNumber value to be assigned to property taxNumber
     */
	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

    /**
     * Getter method for property <tt>invoiceContent</tt>.
     *
     * @return property value of invoiceContent
     */
	public String getInvoiceContent() {
		return invoiceContent;
	}
	
	/**
	 * Setter method for property <tt>invoiceContent</tt>.
	 * 
	 * @param invoiceContent value to be assigned to property invoiceContent
     */
	public void setInvoiceContent(String invoiceContent) {
		this.invoiceContent = invoiceContent;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>printStatus</tt>.
     *
     * @return property value of printStatus
     */
	public String getPrintStatus() {
		return printStatus;
	}
	
	/**
	 * Setter method for property <tt>printStatus</tt>.
	 * 
	 * @param printStatus value to be assigned to property printStatus
     */
	public void setPrintStatus(String printStatus) {
		this.printStatus = printStatus;
	}

    /**
     * Getter method for property <tt>comBank</tt>.
     *
     * @return property value of comBank
     */
	public String getComBank() {
		return comBank;
	}
	
	/**
	 * Setter method for property <tt>comBank</tt>.
	 * 
	 * @param comBank value to be assigned to property comBank
     */
	public void setComBank(String comBank) {
		this.comBank = comBank;
	}

    /**
     * Getter method for property <tt>comAddress</tt>.
     *
     * @return property value of comAddress
     */
	public String getComAddress() {
		return comAddress;
	}
	
	/**
	 * Setter method for property <tt>comAddress</tt>.
	 * 
	 * @param comAddress value to be assigned to property comAddress
     */
	public void setComAddress(String comAddress) {
		this.comAddress = comAddress;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
}
