/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import com.onway.common.lang.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_order_rebate</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_order_rebate.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: OrderRebateDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class OrderRebateDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>CHILD_ORDER_ID</tt>.
	 */
	private String childOrderId;

	/**
	 * This property corresponds to db column <tt>REBATE_TYPE</tt>.
	 */
	private String rebateType;

	/**
	 * This property corresponds to db column <tt>HU_AMOUNT</tt>.
	 */
	private Money huAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>HU_TEMP_AMOUNT</tt>.
	 */
	private Money huTempAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>POINT_AMOUNT</tt>.
	 */
	private Money pointAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>POINT_TEMP_AMOUNT</tt>.
	 */
	private Money pointTempAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>END_DATE</tt>.
	 */
	private Date endDate;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>childOrderId</tt>.
     *
     * @return property value of childOrderId
     */
	public String getChildOrderId() {
		return childOrderId;
	}
	
	/**
	 * Setter method for property <tt>childOrderId</tt>.
	 * 
	 * @param childOrderId value to be assigned to property childOrderId
     */
	public void setChildOrderId(String childOrderId) {
		this.childOrderId = childOrderId;
	}

    /**
     * Getter method for property <tt>rebateType</tt>.
     *
     * @return property value of rebateType
     */
	public String getRebateType() {
		return rebateType;
	}
	
	/**
	 * Setter method for property <tt>rebateType</tt>.
	 * 
	 * @param rebateType value to be assigned to property rebateType
     */
	public void setRebateType(String rebateType) {
		this.rebateType = rebateType;
	}

    /**
     * Getter method for property <tt>huAmount</tt>.
     *
     * @return property value of huAmount
     */
	public Money getHuAmount() {
		return huAmount;
	}
	
	/**
	 * Setter method for property <tt>huAmount</tt>.
	 * 
	 * @param huAmount value to be assigned to property huAmount
     */
	public void setHuAmount(Money huAmount) {
		if (huAmount == null) {
			this.huAmount = new Money(0, 0);
		} else {
			this.huAmount = huAmount;
		}
	}

    /**
     * Getter method for property <tt>huTempAmount</tt>.
     *
     * @return property value of huTempAmount
     */
	public Money getHuTempAmount() {
		return huTempAmount;
	}
	
	/**
	 * Setter method for property <tt>huTempAmount</tt>.
	 * 
	 * @param huTempAmount value to be assigned to property huTempAmount
     */
	public void setHuTempAmount(Money huTempAmount) {
		if (huTempAmount == null) {
			this.huTempAmount = new Money(0, 0);
		} else {
			this.huTempAmount = huTempAmount;
		}
	}

    /**
     * Getter method for property <tt>pointAmount</tt>.
     *
     * @return property value of pointAmount
     */
	public Money getPointAmount() {
		return pointAmount;
	}
	
	/**
	 * Setter method for property <tt>pointAmount</tt>.
	 * 
	 * @param pointAmount value to be assigned to property pointAmount
     */
	public void setPointAmount(Money pointAmount) {
		if (pointAmount == null) {
			this.pointAmount = new Money(0, 0);
		} else {
			this.pointAmount = pointAmount;
		}
	}

    /**
     * Getter method for property <tt>pointTempAmount</tt>.
     *
     * @return property value of pointTempAmount
     */
	public Money getPointTempAmount() {
		return pointTempAmount;
	}
	
	/**
	 * Setter method for property <tt>pointTempAmount</tt>.
	 * 
	 * @param pointTempAmount value to be assigned to property pointTempAmount
     */
	public void setPointTempAmount(Money pointTempAmount) {
		if (pointTempAmount == null) {
			this.pointTempAmount = new Money(0, 0);
		} else {
			this.pointTempAmount = pointTempAmount;
		}
	}

    /**
     * Getter method for property <tt>endDate</tt>.
     *
     * @return property value of endDate
     */
	public Date getEndDate() {
		return endDate;
	}
	
	/**
	 * Setter method for property <tt>endDate</tt>.
	 * 
	 * @param endDate value to be assigned to property endDate
     */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
