/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import com.onway.common.lang.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_order</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_order.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: OrderDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class OrderDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>ORDER_ID</tt>.
	 */
	private String orderId;

	/**
	 * This property corresponds to db column <tt>CHILD_ORDER_ID</tt>.
	 */
	private String childOrderId;

	/**
	 * This property corresponds to db column <tt>RECOMMEND_ID</tt>.
	 */
	private String recommendId;

	/**
	 * This property corresponds to db column <tt>RECOMMEND_USER_ID</tt>.
	 */
	private String recommendUserId;

	/**
	 * This property corresponds to db column <tt>RECOMMEND_TYPE</tt>.
	 */
	private String recommendType;

	/**
	 * This property corresponds to db column <tt>REAL_ORDER_PRICE</tt>.
	 */
	private Money realOrderPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>ORDER_PRICE</tt>.
	 */
	private Money orderPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>CHILD_ORDER_PRICE</tt>.
	 */
	private Money childOrderPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>DPRICE_ID</tt>.
	 */
	private String dpriceId;

	/**
	 * This property corresponds to db column <tt>REAL_POINT_PRICE</tt>.
	 */
	private Money realPointPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>POINT_PRICE</tt>.
	 */
	private Money pointPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>ORDER_COUNT</tt>.
	 */
	private double orderCount;

	/**
	 * This property corresponds to db column <tt>PRODUCT_PRICE</tt>.
	 */
	private Money productPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>PRODUCT_OLD_PRICE</tt>.
	 */
	private Money productOldPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>PRODUCT_ID</tt>.
	 */
	private String productId;

	/**
	 * This property corresponds to db column <tt>PRODUCT_NAME</tt>.
	 */
	private String productName;

	/**
	 * This property corresponds to db column <tt>TEAM_ID</tt>.
	 */
	private String teamId;

	/**
	 * This property corresponds to db column <tt>LUGGAGE</tt>.
	 */
	private Money luggage = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>PAY_WAY</tt>.
	 */
	private String payWay;

	/**
	 * This property corresponds to db column <tt>PAY_STATE</tt>.
	 */
	private String payState;

	/**
	 * This property corresponds to db column <tt>PAY_NO</tt>.
	 */
	private String payNo;

	/**
	 * This property corresponds to db column <tt>ORDER_STATE</tt>.
	 */
	private String orderState;

	/**
	 * This property corresponds to db column <tt>SUB_ORDER_STATUS</tt>.
	 */
	private String subOrderStatus;

	/**
	 * This property corresponds to db column <tt>PRODUCT_TYPE</tt>.
	 */
	private String productType;

	/**
	 * This property corresponds to db column <tt>ORDER_DATE</tt>.
	 */
	private Date orderDate;

	/**
	 * This property corresponds to db column <tt>PAY_DATE</tt>.
	 */
	private Date payDate;

	/**
	 * This property corresponds to db column <tt>RE_USER_NAME</tt>.
	 */
	private String reUserName;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>PROVINCE</tt>.
	 */
	private String province;

	/**
	 * This property corresponds to db column <tt>CITY</tt>.
	 */
	private String city;

	/**
	 * This property corresponds to db column <tt>AREA</tt>.
	 */
	private String area;

	/**
	 * This property corresponds to db column <tt>RE_ADDR</tt>.
	 */
	private String reAddr;

	/**
	 * This property corresponds to db column <tt>TRANSFER_TYPE</tt>.
	 */
	private String transferType;

	/**
	 * This property corresponds to db column <tt>CARRI_COM</tt>.
	 */
	private String carriCom;

	/**
	 * This property corresponds to db column <tt>CARRI_NO</tt>.
	 */
	private String carriNo;

	/**
	 * This property corresponds to db column <tt>REDUCE_TYPE</tt>.
	 */
	private String reduceType;

	/**
	 * This property corresponds to db column <tt>REDUCE_POINT</tt>.
	 */
	private Money reducePoint = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>REDUCE_POINT_MONEY</tt>.
	 */
	private Money reducePointMoney = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>REDUCE_AMOUNT</tt>.
	 */
	private Money reduceAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>REDUCE_AMOUNT_PLAN</tt>.
	 */
	private Money reduceAmountPlan = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>REDUCE_AMOUNT_TEMP</tt>.
	 */
	private Money reduceAmountTemp = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>REDUCE_AMOUNT_VOUCHER</tt>.
	 */
	private Money reduceAmountVoucher = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>INVOICE_NO</tt>.
	 */
	private String invoiceNo;

	/**
	 * This property corresponds to db column <tt>VOUCHER_NO</tt>.
	 */
	private String voucherNo;

	/**
	 * This property corresponds to db column <tt>VOUCHER_CODE</tt>.
	 */
	private String voucherCode;

	/**
	 * This property corresponds to db column <tt>SEND_DATE</tt>.
	 */
	private Date sendDate;

	/**
	 * This property corresponds to db column <tt>COMPLETE_DATE</tt>.
	 */
	private Date completeDate;

	/**
	 * This property corresponds to db column <tt>REASION</tt>.
	 */
	private String reasion;

	/**
	 * This property corresponds to db column <tt>REASION_USER</tt>.
	 */
	private String reasionUser;

	/**
	 * This property corresponds to db column <tt>REASION_TIME</tt>.
	 */
	private Date reasionTime;

	/**
	 * This property corresponds to db column <tt>REASON_BANS</tt>.
	 */
	private String reasonBans;

	/**
	 * This property corresponds to db column <tt>REASON_BANS_USER</tt>.
	 */
	private String reasonBansUser;

	/**
	 * This property corresponds to db column <tt>REASON_BANS_TIME</tt>.
	 */
	private Date reasonBansTime;

	/**
	 * This property corresponds to db column <tt>STOCK_ID</tt>.
	 */
	private int stockId;

	/**
	 * This property corresponds to db column <tt>ATTR_IDS</tt>.
	 */
	private String attrIds;

	/**
	 * This property corresponds to db column <tt>ATTR_NAMES</tt>.
	 */
	private String attrNames;

	/**
	 * This property corresponds to db column <tt>VALUE_IDS</tt>.
	 */
	private String valueIds;

	/**
	 * This property corresponds to db column <tt>VALUEES</tt>.
	 */
	private String valuees;

	/**
	 * This property corresponds to db column <tt>IMG_SRC</tt>.
	 */
	private String imgSrc;

	/**
	 * This property corresponds to db column <tt>SERVICE_TIMES</tt>.
	 */
	private double serviceTimes;

	/**
	 * This property corresponds to db column <tt>REDUCE_PLAT</tt>.
	 */
	private String reducePlat;

	/**
	 * This property corresponds to db column <tt>REDUCE_PRO</tt>.
	 */
	private String reducePro;

	/**
	 * This property corresponds to db column <tt>REDUCE_TEAM</tt>.
	 */
	private String reduceTeam;

	/**
	 * This property corresponds to db column <tt>VOUCHER</tt>.
	 */
	private String voucher;

	/**
	 * This property corresponds to db column <tt>VOUCHER_IMG</tt>.
	 */
	private String voucherImg;

	/**
	 * This property corresponds to db column <tt>DICOUNT</tt>.
	 */
	private double dicount;

	/**
	 * This property corresponds to db column <tt>DICOUNT_MONEY</tt>.
	 */
	private Money dicountMoney = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>CASHIER_DISCOUNT</tt>.
	 */
	private double cashierDiscount;

	/**
	 * This property corresponds to db column <tt>CASHIER_USER</tt>.
	 */
	private String cashierUser;

	/**
	 * This property corresponds to db column <tt>PICK_NO</tt>.
	 */
	private String pickNo;

	/**
	 * This property corresponds to db column <tt>ERR_FLG</tt>.
	 */
	private String errFlg;

	/**
	 * This property corresponds to db column <tt>DEVOTE_AMOUNT</tt>.
	 */
	private Money devoteAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>DEVOTE_AMOUNT_TO</tt>.
	 */
	private String devoteAmountTo;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>CHECK_STEP</tt>.
	 */
	private String checkStep;

	/**
	 * This property corresponds to db column <tt>DELAY_FLG</tt>.
	 */
	private String delayFlg;

	/**
	 * This property corresponds to db column <tt>DELAY_TIME</tt>.
	 */
	private Date delayTime;

	/**
	 * This property corresponds to db column <tt>THIS_RETURN_ID</tt>.
	 */
	private int thisReturnId;

	/**
	 * This property corresponds to db column <tt>VOUCHER_FLG</tt>.
	 */
	private String voucherFlg;

	/**
	 * This property corresponds to db column <tt>PRINT_FLG</tt>.
	 */
	private String printFlg;

	/**
	 * This property corresponds to db column <tt>IS_SC</tt>.
	 */
	private boolean isSc;

	/**
	 * This property corresponds to db column <tt>GMT_SC</tt>.
	 */
	private Date gmtSc;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>orderId</tt>.
     *
     * @return property value of orderId
     */
	public String getOrderId() {
		return orderId;
	}
	
	/**
	 * Setter method for property <tt>orderId</tt>.
	 * 
	 * @param orderId value to be assigned to property orderId
     */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

    /**
     * Getter method for property <tt>childOrderId</tt>.
     *
     * @return property value of childOrderId
     */
	public String getChildOrderId() {
		return childOrderId;
	}
	
	/**
	 * Setter method for property <tt>childOrderId</tt>.
	 * 
	 * @param childOrderId value to be assigned to property childOrderId
     */
	public void setChildOrderId(String childOrderId) {
		this.childOrderId = childOrderId;
	}

    /**
     * Getter method for property <tt>recommendId</tt>.
     *
     * @return property value of recommendId
     */
	public String getRecommendId() {
		return recommendId;
	}
	
	/**
	 * Setter method for property <tt>recommendId</tt>.
	 * 
	 * @param recommendId value to be assigned to property recommendId
     */
	public void setRecommendId(String recommendId) {
		this.recommendId = recommendId;
	}

    /**
     * Getter method for property <tt>recommendUserId</tt>.
     *
     * @return property value of recommendUserId
     */
	public String getRecommendUserId() {
		return recommendUserId;
	}
	
	/**
	 * Setter method for property <tt>recommendUserId</tt>.
	 * 
	 * @param recommendUserId value to be assigned to property recommendUserId
     */
	public void setRecommendUserId(String recommendUserId) {
		this.recommendUserId = recommendUserId;
	}

    /**
     * Getter method for property <tt>recommendType</tt>.
     *
     * @return property value of recommendType
     */
	public String getRecommendType() {
		return recommendType;
	}
	
	/**
	 * Setter method for property <tt>recommendType</tt>.
	 * 
	 * @param recommendType value to be assigned to property recommendType
     */
	public void setRecommendType(String recommendType) {
		this.recommendType = recommendType;
	}

    /**
     * Getter method for property <tt>realOrderPrice</tt>.
     *
     * @return property value of realOrderPrice
     */
	public Money getRealOrderPrice() {
		return realOrderPrice;
	}
	
	/**
	 * Setter method for property <tt>realOrderPrice</tt>.
	 * 
	 * @param realOrderPrice value to be assigned to property realOrderPrice
     */
	public void setRealOrderPrice(Money realOrderPrice) {
		if (realOrderPrice == null) {
			this.realOrderPrice = new Money(0, 0);
		} else {
			this.realOrderPrice = realOrderPrice;
		}
	}

    /**
     * Getter method for property <tt>orderPrice</tt>.
     *
     * @return property value of orderPrice
     */
	public Money getOrderPrice() {
		return orderPrice;
	}
	
	/**
	 * Setter method for property <tt>orderPrice</tt>.
	 * 
	 * @param orderPrice value to be assigned to property orderPrice
     */
	public void setOrderPrice(Money orderPrice) {
		if (orderPrice == null) {
			this.orderPrice = new Money(0, 0);
		} else {
			this.orderPrice = orderPrice;
		}
	}

    /**
     * Getter method for property <tt>childOrderPrice</tt>.
     *
     * @return property value of childOrderPrice
     */
	public Money getChildOrderPrice() {
		return childOrderPrice;
	}
	
	/**
	 * Setter method for property <tt>childOrderPrice</tt>.
	 * 
	 * @param childOrderPrice value to be assigned to property childOrderPrice
     */
	public void setChildOrderPrice(Money childOrderPrice) {
		if (childOrderPrice == null) {
			this.childOrderPrice = new Money(0, 0);
		} else {
			this.childOrderPrice = childOrderPrice;
		}
	}

    /**
     * Getter method for property <tt>dpriceId</tt>.
     *
     * @return property value of dpriceId
     */
	public String getDpriceId() {
		return dpriceId;
	}
	
	/**
	 * Setter method for property <tt>dpriceId</tt>.
	 * 
	 * @param dpriceId value to be assigned to property dpriceId
     */
	public void setDpriceId(String dpriceId) {
		this.dpriceId = dpriceId;
	}

    /**
     * Getter method for property <tt>realPointPrice</tt>.
     *
     * @return property value of realPointPrice
     */
	public Money getRealPointPrice() {
		return realPointPrice;
	}
	
	/**
	 * Setter method for property <tt>realPointPrice</tt>.
	 * 
	 * @param realPointPrice value to be assigned to property realPointPrice
     */
	public void setRealPointPrice(Money realPointPrice) {
		if (realPointPrice == null) {
			this.realPointPrice = new Money(0, 0);
		} else {
			this.realPointPrice = realPointPrice;
		}
	}

    /**
     * Getter method for property <tt>pointPrice</tt>.
     *
     * @return property value of pointPrice
     */
	public Money getPointPrice() {
		return pointPrice;
	}
	
	/**
	 * Setter method for property <tt>pointPrice</tt>.
	 * 
	 * @param pointPrice value to be assigned to property pointPrice
     */
	public void setPointPrice(Money pointPrice) {
		if (pointPrice == null) {
			this.pointPrice = new Money(0, 0);
		} else {
			this.pointPrice = pointPrice;
		}
	}

    /**
     * Getter method for property <tt>orderCount</tt>.
     *
     * @return property value of orderCount
     */
	public double getOrderCount() {
		return orderCount;
	}
	
	/**
	 * Setter method for property <tt>orderCount</tt>.
	 * 
	 * @param orderCount value to be assigned to property orderCount
     */
	public void setOrderCount(double orderCount) {
		this.orderCount = orderCount;
	}

    /**
     * Getter method for property <tt>productPrice</tt>.
     *
     * @return property value of productPrice
     */
	public Money getProductPrice() {
		return productPrice;
	}
	
	/**
	 * Setter method for property <tt>productPrice</tt>.
	 * 
	 * @param productPrice value to be assigned to property productPrice
     */
	public void setProductPrice(Money productPrice) {
		if (productPrice == null) {
			this.productPrice = new Money(0, 0);
		} else {
			this.productPrice = productPrice;
		}
	}

    /**
     * Getter method for property <tt>productOldPrice</tt>.
     *
     * @return property value of productOldPrice
     */
	public Money getProductOldPrice() {
		return productOldPrice;
	}
	
	/**
	 * Setter method for property <tt>productOldPrice</tt>.
	 * 
	 * @param productOldPrice value to be assigned to property productOldPrice
     */
	public void setProductOldPrice(Money productOldPrice) {
		if (productOldPrice == null) {
			this.productOldPrice = new Money(0, 0);
		} else {
			this.productOldPrice = productOldPrice;
		}
	}

    /**
     * Getter method for property <tt>productId</tt>.
     *
     * @return property value of productId
     */
	public String getProductId() {
		return productId;
	}
	
	/**
	 * Setter method for property <tt>productId</tt>.
	 * 
	 * @param productId value to be assigned to property productId
     */
	public void setProductId(String productId) {
		this.productId = productId;
	}

    /**
     * Getter method for property <tt>productName</tt>.
     *
     * @return property value of productName
     */
	public String getProductName() {
		return productName;
	}
	
	/**
	 * Setter method for property <tt>productName</tt>.
	 * 
	 * @param productName value to be assigned to property productName
     */
	public void setProductName(String productName) {
		this.productName = productName;
	}

    /**
     * Getter method for property <tt>teamId</tt>.
     *
     * @return property value of teamId
     */
	public String getTeamId() {
		return teamId;
	}
	
	/**
	 * Setter method for property <tt>teamId</tt>.
	 * 
	 * @param teamId value to be assigned to property teamId
     */
	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

    /**
     * Getter method for property <tt>luggage</tt>.
     *
     * @return property value of luggage
     */
	public Money getLuggage() {
		return luggage;
	}
	
	/**
	 * Setter method for property <tt>luggage</tt>.
	 * 
	 * @param luggage value to be assigned to property luggage
     */
	public void setLuggage(Money luggage) {
		if (luggage == null) {
			this.luggage = new Money(0, 0);
		} else {
			this.luggage = luggage;
		}
	}

    /**
     * Getter method for property <tt>payWay</tt>.
     *
     * @return property value of payWay
     */
	public String getPayWay() {
		return payWay;
	}
	
	/**
	 * Setter method for property <tt>payWay</tt>.
	 * 
	 * @param payWay value to be assigned to property payWay
     */
	public void setPayWay(String payWay) {
		this.payWay = payWay;
	}

    /**
     * Getter method for property <tt>payState</tt>.
     *
     * @return property value of payState
     */
	public String getPayState() {
		return payState;
	}
	
	/**
	 * Setter method for property <tt>payState</tt>.
	 * 
	 * @param payState value to be assigned to property payState
     */
	public void setPayState(String payState) {
		this.payState = payState;
	}

    /**
     * Getter method for property <tt>payNo</tt>.
     *
     * @return property value of payNo
     */
	public String getPayNo() {
		return payNo;
	}
	
	/**
	 * Setter method for property <tt>payNo</tt>.
	 * 
	 * @param payNo value to be assigned to property payNo
     */
	public void setPayNo(String payNo) {
		this.payNo = payNo;
	}

    /**
     * Getter method for property <tt>orderState</tt>.
     *
     * @return property value of orderState
     */
	public String getOrderState() {
		return orderState;
	}
	
	/**
	 * Setter method for property <tt>orderState</tt>.
	 * 
	 * @param orderState value to be assigned to property orderState
     */
	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

    /**
     * Getter method for property <tt>subOrderStatus</tt>.
     *
     * @return property value of subOrderStatus
     */
	public String getSubOrderStatus() {
		return subOrderStatus;
	}
	
	/**
	 * Setter method for property <tt>subOrderStatus</tt>.
	 * 
	 * @param subOrderStatus value to be assigned to property subOrderStatus
     */
	public void setSubOrderStatus(String subOrderStatus) {
		this.subOrderStatus = subOrderStatus;
	}

    /**
     * Getter method for property <tt>productType</tt>.
     *
     * @return property value of productType
     */
	public String getProductType() {
		return productType;
	}
	
	/**
	 * Setter method for property <tt>productType</tt>.
	 * 
	 * @param productType value to be assigned to property productType
     */
	public void setProductType(String productType) {
		this.productType = productType;
	}

    /**
     * Getter method for property <tt>orderDate</tt>.
     *
     * @return property value of orderDate
     */
	public Date getOrderDate() {
		return orderDate;
	}
	
	/**
	 * Setter method for property <tt>orderDate</tt>.
	 * 
	 * @param orderDate value to be assigned to property orderDate
     */
	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

    /**
     * Getter method for property <tt>payDate</tt>.
     *
     * @return property value of payDate
     */
	public Date getPayDate() {
		return payDate;
	}
	
	/**
	 * Setter method for property <tt>payDate</tt>.
	 * 
	 * @param payDate value to be assigned to property payDate
     */
	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

    /**
     * Getter method for property <tt>reUserName</tt>.
     *
     * @return property value of reUserName
     */
	public String getReUserName() {
		return reUserName;
	}
	
	/**
	 * Setter method for property <tt>reUserName</tt>.
	 * 
	 * @param reUserName value to be assigned to property reUserName
     */
	public void setReUserName(String reUserName) {
		this.reUserName = reUserName;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>province</tt>.
     *
     * @return property value of province
     */
	public String getProvince() {
		return province;
	}
	
	/**
	 * Setter method for property <tt>province</tt>.
	 * 
	 * @param province value to be assigned to property province
     */
	public void setProvince(String province) {
		this.province = province;
	}

    /**
     * Getter method for property <tt>city</tt>.
     *
     * @return property value of city
     */
	public String getCity() {
		return city;
	}
	
	/**
	 * Setter method for property <tt>city</tt>.
	 * 
	 * @param city value to be assigned to property city
     */
	public void setCity(String city) {
		this.city = city;
	}

    /**
     * Getter method for property <tt>area</tt>.
     *
     * @return property value of area
     */
	public String getArea() {
		return area;
	}
	
	/**
	 * Setter method for property <tt>area</tt>.
	 * 
	 * @param area value to be assigned to property area
     */
	public void setArea(String area) {
		this.area = area;
	}

    /**
     * Getter method for property <tt>reAddr</tt>.
     *
     * @return property value of reAddr
     */
	public String getReAddr() {
		return reAddr;
	}
	
	/**
	 * Setter method for property <tt>reAddr</tt>.
	 * 
	 * @param reAddr value to be assigned to property reAddr
     */
	public void setReAddr(String reAddr) {
		this.reAddr = reAddr;
	}

    /**
     * Getter method for property <tt>transferType</tt>.
     *
     * @return property value of transferType
     */
	public String getTransferType() {
		return transferType;
	}
	
	/**
	 * Setter method for property <tt>transferType</tt>.
	 * 
	 * @param transferType value to be assigned to property transferType
     */
	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

    /**
     * Getter method for property <tt>carriCom</tt>.
     *
     * @return property value of carriCom
     */
	public String getCarriCom() {
		return carriCom;
	}
	
	/**
	 * Setter method for property <tt>carriCom</tt>.
	 * 
	 * @param carriCom value to be assigned to property carriCom
     */
	public void setCarriCom(String carriCom) {
		this.carriCom = carriCom;
	}

    /**
     * Getter method for property <tt>carriNo</tt>.
     *
     * @return property value of carriNo
     */
	public String getCarriNo() {
		return carriNo;
	}
	
	/**
	 * Setter method for property <tt>carriNo</tt>.
	 * 
	 * @param carriNo value to be assigned to property carriNo
     */
	public void setCarriNo(String carriNo) {
		this.carriNo = carriNo;
	}

    /**
     * Getter method for property <tt>reduceType</tt>.
     *
     * @return property value of reduceType
     */
	public String getReduceType() {
		return reduceType;
	}
	
	/**
	 * Setter method for property <tt>reduceType</tt>.
	 * 
	 * @param reduceType value to be assigned to property reduceType
     */
	public void setReduceType(String reduceType) {
		this.reduceType = reduceType;
	}

    /**
     * Getter method for property <tt>reducePoint</tt>.
     *
     * @return property value of reducePoint
     */
	public Money getReducePoint() {
		return reducePoint;
	}
	
	/**
	 * Setter method for property <tt>reducePoint</tt>.
	 * 
	 * @param reducePoint value to be assigned to property reducePoint
     */
	public void setReducePoint(Money reducePoint) {
		if (reducePoint == null) {
			this.reducePoint = new Money(0, 0);
		} else {
			this.reducePoint = reducePoint;
		}
	}

    /**
     * Getter method for property <tt>reducePointMoney</tt>.
     *
     * @return property value of reducePointMoney
     */
	public Money getReducePointMoney() {
		return reducePointMoney;
	}
	
	/**
	 * Setter method for property <tt>reducePointMoney</tt>.
	 * 
	 * @param reducePointMoney value to be assigned to property reducePointMoney
     */
	public void setReducePointMoney(Money reducePointMoney) {
		if (reducePointMoney == null) {
			this.reducePointMoney = new Money(0, 0);
		} else {
			this.reducePointMoney = reducePointMoney;
		}
	}

    /**
     * Getter method for property <tt>reduceAmount</tt>.
     *
     * @return property value of reduceAmount
     */
	public Money getReduceAmount() {
		return reduceAmount;
	}
	
	/**
	 * Setter method for property <tt>reduceAmount</tt>.
	 * 
	 * @param reduceAmount value to be assigned to property reduceAmount
     */
	public void setReduceAmount(Money reduceAmount) {
		if (reduceAmount == null) {
			this.reduceAmount = new Money(0, 0);
		} else {
			this.reduceAmount = reduceAmount;
		}
	}

    /**
     * Getter method for property <tt>reduceAmountPlan</tt>.
     *
     * @return property value of reduceAmountPlan
     */
	public Money getReduceAmountPlan() {
		return reduceAmountPlan;
	}
	
	/**
	 * Setter method for property <tt>reduceAmountPlan</tt>.
	 * 
	 * @param reduceAmountPlan value to be assigned to property reduceAmountPlan
     */
	public void setReduceAmountPlan(Money reduceAmountPlan) {
		if (reduceAmountPlan == null) {
			this.reduceAmountPlan = new Money(0, 0);
		} else {
			this.reduceAmountPlan = reduceAmountPlan;
		}
	}

    /**
     * Getter method for property <tt>reduceAmountTemp</tt>.
     *
     * @return property value of reduceAmountTemp
     */
	public Money getReduceAmountTemp() {
		return reduceAmountTemp;
	}
	
	/**
	 * Setter method for property <tt>reduceAmountTemp</tt>.
	 * 
	 * @param reduceAmountTemp value to be assigned to property reduceAmountTemp
     */
	public void setReduceAmountTemp(Money reduceAmountTemp) {
		if (reduceAmountTemp == null) {
			this.reduceAmountTemp = new Money(0, 0);
		} else {
			this.reduceAmountTemp = reduceAmountTemp;
		}
	}

    /**
     * Getter method for property <tt>reduceAmountVoucher</tt>.
     *
     * @return property value of reduceAmountVoucher
     */
	public Money getReduceAmountVoucher() {
		return reduceAmountVoucher;
	}
	
	/**
	 * Setter method for property <tt>reduceAmountVoucher</tt>.
	 * 
	 * @param reduceAmountVoucher value to be assigned to property reduceAmountVoucher
     */
	public void setReduceAmountVoucher(Money reduceAmountVoucher) {
		if (reduceAmountVoucher == null) {
			this.reduceAmountVoucher = new Money(0, 0);
		} else {
			this.reduceAmountVoucher = reduceAmountVoucher;
		}
	}

    /**
     * Getter method for property <tt>invoiceNo</tt>.
     *
     * @return property value of invoiceNo
     */
	public String getInvoiceNo() {
		return invoiceNo;
	}
	
	/**
	 * Setter method for property <tt>invoiceNo</tt>.
	 * 
	 * @param invoiceNo value to be assigned to property invoiceNo
     */
	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

    /**
     * Getter method for property <tt>voucherNo</tt>.
     *
     * @return property value of voucherNo
     */
	public String getVoucherNo() {
		return voucherNo;
	}
	
	/**
	 * Setter method for property <tt>voucherNo</tt>.
	 * 
	 * @param voucherNo value to be assigned to property voucherNo
     */
	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

    /**
     * Getter method for property <tt>voucherCode</tt>.
     *
     * @return property value of voucherCode
     */
	public String getVoucherCode() {
		return voucherCode;
	}
	
	/**
	 * Setter method for property <tt>voucherCode</tt>.
	 * 
	 * @param voucherCode value to be assigned to property voucherCode
     */
	public void setVoucherCode(String voucherCode) {
		this.voucherCode = voucherCode;
	}

    /**
     * Getter method for property <tt>sendDate</tt>.
     *
     * @return property value of sendDate
     */
	public Date getSendDate() {
		return sendDate;
	}
	
	/**
	 * Setter method for property <tt>sendDate</tt>.
	 * 
	 * @param sendDate value to be assigned to property sendDate
     */
	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

    /**
     * Getter method for property <tt>completeDate</tt>.
     *
     * @return property value of completeDate
     */
	public Date getCompleteDate() {
		return completeDate;
	}
	
	/**
	 * Setter method for property <tt>completeDate</tt>.
	 * 
	 * @param completeDate value to be assigned to property completeDate
     */
	public void setCompleteDate(Date completeDate) {
		this.completeDate = completeDate;
	}

    /**
     * Getter method for property <tt>reasion</tt>.
     *
     * @return property value of reasion
     */
	public String getReasion() {
		return reasion;
	}
	
	/**
	 * Setter method for property <tt>reasion</tt>.
	 * 
	 * @param reasion value to be assigned to property reasion
     */
	public void setReasion(String reasion) {
		this.reasion = reasion;
	}

    /**
     * Getter method for property <tt>reasionUser</tt>.
     *
     * @return property value of reasionUser
     */
	public String getReasionUser() {
		return reasionUser;
	}
	
	/**
	 * Setter method for property <tt>reasionUser</tt>.
	 * 
	 * @param reasionUser value to be assigned to property reasionUser
     */
	public void setReasionUser(String reasionUser) {
		this.reasionUser = reasionUser;
	}

    /**
     * Getter method for property <tt>reasionTime</tt>.
     *
     * @return property value of reasionTime
     */
	public Date getReasionTime() {
		return reasionTime;
	}
	
	/**
	 * Setter method for property <tt>reasionTime</tt>.
	 * 
	 * @param reasionTime value to be assigned to property reasionTime
     */
	public void setReasionTime(Date reasionTime) {
		this.reasionTime = reasionTime;
	}

    /**
     * Getter method for property <tt>reasonBans</tt>.
     *
     * @return property value of reasonBans
     */
	public String getReasonBans() {
		return reasonBans;
	}
	
	/**
	 * Setter method for property <tt>reasonBans</tt>.
	 * 
	 * @param reasonBans value to be assigned to property reasonBans
     */
	public void setReasonBans(String reasonBans) {
		this.reasonBans = reasonBans;
	}

    /**
     * Getter method for property <tt>reasonBansUser</tt>.
     *
     * @return property value of reasonBansUser
     */
	public String getReasonBansUser() {
		return reasonBansUser;
	}
	
	/**
	 * Setter method for property <tt>reasonBansUser</tt>.
	 * 
	 * @param reasonBansUser value to be assigned to property reasonBansUser
     */
	public void setReasonBansUser(String reasonBansUser) {
		this.reasonBansUser = reasonBansUser;
	}

    /**
     * Getter method for property <tt>reasonBansTime</tt>.
     *
     * @return property value of reasonBansTime
     */
	public Date getReasonBansTime() {
		return reasonBansTime;
	}
	
	/**
	 * Setter method for property <tt>reasonBansTime</tt>.
	 * 
	 * @param reasonBansTime value to be assigned to property reasonBansTime
     */
	public void setReasonBansTime(Date reasonBansTime) {
		this.reasonBansTime = reasonBansTime;
	}

    /**
     * Getter method for property <tt>stockId</tt>.
     *
     * @return property value of stockId
     */
	public int getStockId() {
		return stockId;
	}
	
	/**
	 * Setter method for property <tt>stockId</tt>.
	 * 
	 * @param stockId value to be assigned to property stockId
     */
	public void setStockId(int stockId) {
		this.stockId = stockId;
	}

    /**
     * Getter method for property <tt>attrIds</tt>.
     *
     * @return property value of attrIds
     */
	public String getAttrIds() {
		return attrIds;
	}
	
	/**
	 * Setter method for property <tt>attrIds</tt>.
	 * 
	 * @param attrIds value to be assigned to property attrIds
     */
	public void setAttrIds(String attrIds) {
		this.attrIds = attrIds;
	}

    /**
     * Getter method for property <tt>attrNames</tt>.
     *
     * @return property value of attrNames
     */
	public String getAttrNames() {
		return attrNames;
	}
	
	/**
	 * Setter method for property <tt>attrNames</tt>.
	 * 
	 * @param attrNames value to be assigned to property attrNames
     */
	public void setAttrNames(String attrNames) {
		this.attrNames = attrNames;
	}

    /**
     * Getter method for property <tt>valueIds</tt>.
     *
     * @return property value of valueIds
     */
	public String getValueIds() {
		return valueIds;
	}
	
	/**
	 * Setter method for property <tt>valueIds</tt>.
	 * 
	 * @param valueIds value to be assigned to property valueIds
     */
	public void setValueIds(String valueIds) {
		this.valueIds = valueIds;
	}

    /**
     * Getter method for property <tt>valuees</tt>.
     *
     * @return property value of valuees
     */
	public String getValuees() {
		return valuees;
	}
	
	/**
	 * Setter method for property <tt>valuees</tt>.
	 * 
	 * @param valuees value to be assigned to property valuees
     */
	public void setValuees(String valuees) {
		this.valuees = valuees;
	}

    /**
     * Getter method for property <tt>imgSrc</tt>.
     *
     * @return property value of imgSrc
     */
	public String getImgSrc() {
		return imgSrc;
	}
	
	/**
	 * Setter method for property <tt>imgSrc</tt>.
	 * 
	 * @param imgSrc value to be assigned to property imgSrc
     */
	public void setImgSrc(String imgSrc) {
		this.imgSrc = imgSrc;
	}

    /**
     * Getter method for property <tt>serviceTimes</tt>.
     *
     * @return property value of serviceTimes
     */
	public double getServiceTimes() {
		return serviceTimes;
	}
	
	/**
	 * Setter method for property <tt>serviceTimes</tt>.
	 * 
	 * @param serviceTimes value to be assigned to property serviceTimes
     */
	public void setServiceTimes(double serviceTimes) {
		this.serviceTimes = serviceTimes;
	}

    /**
     * Getter method for property <tt>reducePlat</tt>.
     *
     * @return property value of reducePlat
     */
	public String getReducePlat() {
		return reducePlat;
	}
	
	/**
	 * Setter method for property <tt>reducePlat</tt>.
	 * 
	 * @param reducePlat value to be assigned to property reducePlat
     */
	public void setReducePlat(String reducePlat) {
		this.reducePlat = reducePlat;
	}

    /**
     * Getter method for property <tt>reducePro</tt>.
     *
     * @return property value of reducePro
     */
	public String getReducePro() {
		return reducePro;
	}
	
	/**
	 * Setter method for property <tt>reducePro</tt>.
	 * 
	 * @param reducePro value to be assigned to property reducePro
     */
	public void setReducePro(String reducePro) {
		this.reducePro = reducePro;
	}

    /**
     * Getter method for property <tt>reduceTeam</tt>.
     *
     * @return property value of reduceTeam
     */
	public String getReduceTeam() {
		return reduceTeam;
	}
	
	/**
	 * Setter method for property <tt>reduceTeam</tt>.
	 * 
	 * @param reduceTeam value to be assigned to property reduceTeam
     */
	public void setReduceTeam(String reduceTeam) {
		this.reduceTeam = reduceTeam;
	}

    /**
     * Getter method for property <tt>voucher</tt>.
     *
     * @return property value of voucher
     */
	public String getVoucher() {
		return voucher;
	}
	
	/**
	 * Setter method for property <tt>voucher</tt>.
	 * 
	 * @param voucher value to be assigned to property voucher
     */
	public void setVoucher(String voucher) {
		this.voucher = voucher;
	}

    /**
     * Getter method for property <tt>voucherImg</tt>.
     *
     * @return property value of voucherImg
     */
	public String getVoucherImg() {
		return voucherImg;
	}
	
	/**
	 * Setter method for property <tt>voucherImg</tt>.
	 * 
	 * @param voucherImg value to be assigned to property voucherImg
     */
	public void setVoucherImg(String voucherImg) {
		this.voucherImg = voucherImg;
	}

    /**
     * Getter method for property <tt>dicount</tt>.
     *
     * @return property value of dicount
     */
	public double getDicount() {
		return dicount;
	}
	
	/**
	 * Setter method for property <tt>dicount</tt>.
	 * 
	 * @param dicount value to be assigned to property dicount
     */
	public void setDicount(double dicount) {
		this.dicount = dicount;
	}

    /**
     * Getter method for property <tt>dicountMoney</tt>.
     *
     * @return property value of dicountMoney
     */
	public Money getDicountMoney() {
		return dicountMoney;
	}
	
	/**
	 * Setter method for property <tt>dicountMoney</tt>.
	 * 
	 * @param dicountMoney value to be assigned to property dicountMoney
     */
	public void setDicountMoney(Money dicountMoney) {
		if (dicountMoney == null) {
			this.dicountMoney = new Money(0, 0);
		} else {
			this.dicountMoney = dicountMoney;
		}
	}

    /**
     * Getter method for property <tt>cashierDiscount</tt>.
     *
     * @return property value of cashierDiscount
     */
	public double getCashierDiscount() {
		return cashierDiscount;
	}
	
	/**
	 * Setter method for property <tt>cashierDiscount</tt>.
	 * 
	 * @param cashierDiscount value to be assigned to property cashierDiscount
     */
	public void setCashierDiscount(double cashierDiscount) {
		this.cashierDiscount = cashierDiscount;
	}

    /**
     * Getter method for property <tt>cashierUser</tt>.
     *
     * @return property value of cashierUser
     */
	public String getCashierUser() {
		return cashierUser;
	}
	
	/**
	 * Setter method for property <tt>cashierUser</tt>.
	 * 
	 * @param cashierUser value to be assigned to property cashierUser
     */
	public void setCashierUser(String cashierUser) {
		this.cashierUser = cashierUser;
	}

    /**
     * Getter method for property <tt>pickNo</tt>.
     *
     * @return property value of pickNo
     */
	public String getPickNo() {
		return pickNo;
	}
	
	/**
	 * Setter method for property <tt>pickNo</tt>.
	 * 
	 * @param pickNo value to be assigned to property pickNo
     */
	public void setPickNo(String pickNo) {
		this.pickNo = pickNo;
	}

    /**
     * Getter method for property <tt>errFlg</tt>.
     *
     * @return property value of errFlg
     */
	public String getErrFlg() {
		return errFlg;
	}
	
	/**
	 * Setter method for property <tt>errFlg</tt>.
	 * 
	 * @param errFlg value to be assigned to property errFlg
     */
	public void setErrFlg(String errFlg) {
		this.errFlg = errFlg;
	}

    /**
     * Getter method for property <tt>devoteAmount</tt>.
     *
     * @return property value of devoteAmount
     */
	public Money getDevoteAmount() {
		return devoteAmount;
	}
	
	/**
	 * Setter method for property <tt>devoteAmount</tt>.
	 * 
	 * @param devoteAmount value to be assigned to property devoteAmount
     */
	public void setDevoteAmount(Money devoteAmount) {
		if (devoteAmount == null) {
			this.devoteAmount = new Money(0, 0);
		} else {
			this.devoteAmount = devoteAmount;
		}
	}

    /**
     * Getter method for property <tt>devoteAmountTo</tt>.
     *
     * @return property value of devoteAmountTo
     */
	public String getDevoteAmountTo() {
		return devoteAmountTo;
	}
	
	/**
	 * Setter method for property <tt>devoteAmountTo</tt>.
	 * 
	 * @param devoteAmountTo value to be assigned to property devoteAmountTo
     */
	public void setDevoteAmountTo(String devoteAmountTo) {
		this.devoteAmountTo = devoteAmountTo;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>checkStep</tt>.
     *
     * @return property value of checkStep
     */
	public String getCheckStep() {
		return checkStep;
	}
	
	/**
	 * Setter method for property <tt>checkStep</tt>.
	 * 
	 * @param checkStep value to be assigned to property checkStep
     */
	public void setCheckStep(String checkStep) {
		this.checkStep = checkStep;
	}

    /**
     * Getter method for property <tt>delayFlg</tt>.
     *
     * @return property value of delayFlg
     */
	public String getDelayFlg() {
		return delayFlg;
	}
	
	/**
	 * Setter method for property <tt>delayFlg</tt>.
	 * 
	 * @param delayFlg value to be assigned to property delayFlg
     */
	public void setDelayFlg(String delayFlg) {
		this.delayFlg = delayFlg;
	}

    /**
     * Getter method for property <tt>delayTime</tt>.
     *
     * @return property value of delayTime
     */
	public Date getDelayTime() {
		return delayTime;
	}
	
	/**
	 * Setter method for property <tt>delayTime</tt>.
	 * 
	 * @param delayTime value to be assigned to property delayTime
     */
	public void setDelayTime(Date delayTime) {
		this.delayTime = delayTime;
	}

    /**
     * Getter method for property <tt>thisReturnId</tt>.
     *
     * @return property value of thisReturnId
     */
	public int getThisReturnId() {
		return thisReturnId;
	}
	
	/**
	 * Setter method for property <tt>thisReturnId</tt>.
	 * 
	 * @param thisReturnId value to be assigned to property thisReturnId
     */
	public void setThisReturnId(int thisReturnId) {
		this.thisReturnId = thisReturnId;
	}

    /**
     * Getter method for property <tt>voucherFlg</tt>.
     *
     * @return property value of voucherFlg
     */
	public String getVoucherFlg() {
		return voucherFlg;
	}
	
	/**
	 * Setter method for property <tt>voucherFlg</tt>.
	 * 
	 * @param voucherFlg value to be assigned to property voucherFlg
     */
	public void setVoucherFlg(String voucherFlg) {
		this.voucherFlg = voucherFlg;
	}

    /**
     * Getter method for property <tt>printFlg</tt>.
     *
     * @return property value of printFlg
     */
	public String getPrintFlg() {
		return printFlg;
	}
	
	/**
	 * Setter method for property <tt>printFlg</tt>.
	 * 
	 * @param printFlg value to be assigned to property printFlg
     */
	public void setPrintFlg(String printFlg) {
		this.printFlg = printFlg;
	}

    /**
     * Getter method for property <tt>isSc</tt>.
     *
     * @return property value of isSc
     */
	public boolean isIsSc() {
		return isSc;
	}
	
	/**
	 * Setter method for property <tt>isSc</tt>.
	 * 
	 * @param isSc value to be assigned to property isSc
     */
	public void setIsSc(boolean isSc) {
		this.isSc = isSc;
	}

    /**
     * Getter method for property <tt>gmtSc</tt>.
     *
     * @return property value of gmtSc
     */
	public Date getGmtSc() {
		return gmtSc;
	}
	
	/**
	 * Setter method for property <tt>gmtSc</tt>.
	 * 
	 * @param gmtSc value to be assigned to property gmtSc
     */
	public void setGmtSc(Date gmtSc) {
		this.gmtSc = gmtSc;
	}
}
