/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_order_owe</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_order_owe.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: OrderOweDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class OrderOweDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>ORDER_ID</tt>.
	 */
	private String orderId;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>OWE_IMG</tt>.
	 */
	private String oweImg;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>ASS_ROLE</tt>.
	 */
	private String assRole;

	/**
	 * This property corresponds to db column <tt>FAIL_REASON</tt>.
	 */
	private String failReason;

	/**
	 * This property corresponds to db column <tt>FAIL_USER</tt>.
	 */
	private String failUser;

	/**
	 * This property corresponds to db column <tt>FAIL_TIME</tt>.
	 */
	private Date failTime;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>orderId</tt>.
     *
     * @return property value of orderId
     */
	public String getOrderId() {
		return orderId;
	}
	
	/**
	 * Setter method for property <tt>orderId</tt>.
	 * 
	 * @param orderId value to be assigned to property orderId
     */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>oweImg</tt>.
     *
     * @return property value of oweImg
     */
	public String getOweImg() {
		return oweImg;
	}
	
	/**
	 * Setter method for property <tt>oweImg</tt>.
	 * 
	 * @param oweImg value to be assigned to property oweImg
     */
	public void setOweImg(String oweImg) {
		this.oweImg = oweImg;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>assRole</tt>.
     *
     * @return property value of assRole
     */
	public String getAssRole() {
		return assRole;
	}
	
	/**
	 * Setter method for property <tt>assRole</tt>.
	 * 
	 * @param assRole value to be assigned to property assRole
     */
	public void setAssRole(String assRole) {
		this.assRole = assRole;
	}

    /**
     * Getter method for property <tt>failReason</tt>.
     *
     * @return property value of failReason
     */
	public String getFailReason() {
		return failReason;
	}
	
	/**
	 * Setter method for property <tt>failReason</tt>.
	 * 
	 * @param failReason value to be assigned to property failReason
     */
	public void setFailReason(String failReason) {
		this.failReason = failReason;
	}

    /**
     * Getter method for property <tt>failUser</tt>.
     *
     * @return property value of failUser
     */
	public String getFailUser() {
		return failUser;
	}
	
	/**
	 * Setter method for property <tt>failUser</tt>.
	 * 
	 * @param failUser value to be assigned to property failUser
     */
	public void setFailUser(String failUser) {
		this.failUser = failUser;
	}

    /**
     * Getter method for property <tt>failTime</tt>.
     *
     * @return property value of failTime
     */
	public Date getFailTime() {
		return failTime;
	}
	
	/**
	 * Setter method for property <tt>failTime</tt>.
	 * 
	 * @param failTime value to be assigned to property failTime
     */
	public void setFailTime(Date failTime) {
		this.failTime = failTime;
	}
}
