/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>sys_express</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_express.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: SysExpressDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class SysExpressDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>EXPRESS_NO</tt>.
	 */
	private String expressNo;

	/**
	 * This property corresponds to db column <tt>COM</tt>.
	 */
	private String com;

	/**
	 * This property corresponds to db column <tt>EXPRESS_NAME</tt>.
	 */
	private String expressName;

	/**
	 * This property corresponds to db column <tt>SORT_NUM</tt>.
	 */
	private int sortNum;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>expressNo</tt>.
     *
     * @return property value of expressNo
     */
	public String getExpressNo() {
		return expressNo;
	}
	
	/**
	 * Setter method for property <tt>expressNo</tt>.
	 * 
	 * @param expressNo value to be assigned to property expressNo
     */
	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

    /**
     * Getter method for property <tt>com</tt>.
     *
     * @return property value of com
     */
	public String getCom() {
		return com;
	}
	
	/**
	 * Setter method for property <tt>com</tt>.
	 * 
	 * @param com value to be assigned to property com
     */
	public void setCom(String com) {
		this.com = com;
	}

    /**
     * Getter method for property <tt>expressName</tt>.
     *
     * @return property value of expressName
     */
	public String getExpressName() {
		return expressName;
	}
	
	/**
	 * Setter method for property <tt>expressName</tt>.
	 * 
	 * @param expressName value to be assigned to property expressName
     */
	public void setExpressName(String expressName) {
		this.expressName = expressName;
	}

    /**
     * Getter method for property <tt>sortNum</tt>.
     *
     * @return property value of sortNum
     */
	public int getSortNum() {
		return sortNum;
	}
	
	/**
	 * Setter method for property <tt>sortNum</tt>.
	 * 
	 * @param sortNum value to be assigned to property sortNum
     */
	public void setSortNum(int sortNum) {
		this.sortNum = sortNum;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
