/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;
import com.onway.common.lang.Money;

/**
 * A data object class directly models database table <tt>sys_level</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_level.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: SysLevelDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class SysLevelDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>LEVEL_TYPE</tt>.
	 */
	private String levelType;

	/**
	 * This property corresponds to db column <tt>MIN_AMOUNT</tt>.
	 */
	private Money minAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>MAX_AMOUNT</tt>.
	 */
	private Money maxAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>TYPE</tt>.
	 */
	private String type;

	/**
	 * This property corresponds to db column <tt>DICOUNT_RATE</tt>.
	 */
	private double dicountRate;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>levelType</tt>.
     *
     * @return property value of levelType
     */
	public String getLevelType() {
		return levelType;
	}
	
	/**
	 * Setter method for property <tt>levelType</tt>.
	 * 
	 * @param levelType value to be assigned to property levelType
     */
	public void setLevelType(String levelType) {
		this.levelType = levelType;
	}

    /**
     * Getter method for property <tt>minAmount</tt>.
     *
     * @return property value of minAmount
     */
	public Money getMinAmount() {
		return minAmount;
	}
	
	/**
	 * Setter method for property <tt>minAmount</tt>.
	 * 
	 * @param minAmount value to be assigned to property minAmount
     */
	public void setMinAmount(Money minAmount) {
		if (minAmount == null) {
			this.minAmount = new Money(0, 0);
		} else {
			this.minAmount = minAmount;
		}
	}

    /**
     * Getter method for property <tt>maxAmount</tt>.
     *
     * @return property value of maxAmount
     */
	public Money getMaxAmount() {
		return maxAmount;
	}
	
	/**
	 * Setter method for property <tt>maxAmount</tt>.
	 * 
	 * @param maxAmount value to be assigned to property maxAmount
     */
	public void setMaxAmount(Money maxAmount) {
		if (maxAmount == null) {
			this.maxAmount = new Money(0, 0);
		} else {
			this.maxAmount = maxAmount;
		}
	}

    /**
     * Getter method for property <tt>type</tt>.
     *
     * @return property value of type
     */
	public String getType() {
		return type;
	}
	
	/**
	 * Setter method for property <tt>type</tt>.
	 * 
	 * @param type value to be assigned to property type
     */
	public void setType(String type) {
		this.type = type;
	}

    /**
     * Getter method for property <tt>dicountRate</tt>.
     *
     * @return property value of dicountRate
     */
	public double getDicountRate() {
		return dicountRate;
	}
	
	/**
	 * Setter method for property <tt>dicountRate</tt>.
	 * 
	 * @param dicountRate value to be assigned to property dicountRate
     */
	public void setDicountRate(double dicountRate) {
		this.dicountRate = dicountRate;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
