/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_user</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: UserDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class UserDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>OPEN_ID</tt>.
	 */
	private String openId;

	/**
	 * This property corresponds to db column <tt>UNION_ID</tt>.
	 */
	private String unionId;

	/**
	 * This property corresponds to db column <tt>HEAD_URL</tt>.
	 */
	private String headUrl;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>NICK_NAME</tt>.
	 */
	private String nickName;

	/**
	 * This property corresponds to db column <tt>SEX</tt>.
	 */
	private String sex;

	/**
	 * This property corresponds to db column <tt>AGE</tt>.
	 */
	private int age;

	/**
	 * This property corresponds to db column <tt>CERT_NO</tt>.
	 */
	private String certNo;

	/**
	 * This property corresponds to db column <tt>BIRTHDAY</tt>.
	 */
	private Date birthday;

	/**
	 * This property corresponds to db column <tt>AGE_GROUP</tt>.
	 */
	private String ageGroup;

	/**
	 * This property corresponds to db column <tt>COM_NAME</tt>.
	 */
	private String comName;

	/**
	 * This property corresponds to db column <tt>USER_LEVEL</tt>.
	 */
	private int userLevel;

	/**
	 * This property corresponds to db column <tt>RECOMMEND_USER_ID</tt>.
	 */
	private String recommendUserId;

	/**
	 * This property corresponds to db column <tt>RECOMMEND_USER_TYPE</tt>.
	 */
	private String recommendUserType;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>IS_NEW</tt>.
	 */
	private String isNew;

	/**
	 * This property corresponds to db column <tt>LOGIN_PSW</tt>.
	 */
	private String loginPsw;

	/**
	 * This property corresponds to db column <tt>CAN_WITHDRAW</tt>.
	 */
	private String canWithdraw;

	/**
	 * This property corresponds to db column <tt>REAL_NAME</tt>.
	 */
	private String realName;

	/**
	 * This property corresponds to db column <tt>COM_ADDRESS</tt>.
	 */
	private String comAddress;

	/**
	 * This property corresponds to db column <tt>PROFESSION</tt>.
	 */
	private String profession;

	/**
	 * This property corresponds to db column <tt>COMFIRM_MSG</tt>.
	 */
	private String comfirmMsg;

	/**
	 * This property corresponds to db column <tt>QR_CODE</tt>.
	 */
	private String qrCode;

	/**
	 * This property corresponds to db column <tt>ERP_NO</tt>.
	 */
	private String erpNo;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>openId</tt>.
     *
     * @return property value of openId
     */
	public String getOpenId() {
		return openId;
	}
	
	/**
	 * Setter method for property <tt>openId</tt>.
	 * 
	 * @param openId value to be assigned to property openId
     */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

    /**
     * Getter method for property <tt>unionId</tt>.
     *
     * @return property value of unionId
     */
	public String getUnionId() {
		return unionId;
	}
	
	/**
	 * Setter method for property <tt>unionId</tt>.
	 * 
	 * @param unionId value to be assigned to property unionId
     */
	public void setUnionId(String unionId) {
		this.unionId = unionId;
	}

    /**
     * Getter method for property <tt>headUrl</tt>.
     *
     * @return property value of headUrl
     */
	public String getHeadUrl() {
		return headUrl;
	}
	
	/**
	 * Setter method for property <tt>headUrl</tt>.
	 * 
	 * @param headUrl value to be assigned to property headUrl
     */
	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>nickName</tt>.
     *
     * @return property value of nickName
     */
	public String getNickName() {
		return nickName;
	}
	
	/**
	 * Setter method for property <tt>nickName</tt>.
	 * 
	 * @param nickName value to be assigned to property nickName
     */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

    /**
     * Getter method for property <tt>sex</tt>.
     *
     * @return property value of sex
     */
	public String getSex() {
		return sex;
	}
	
	/**
	 * Setter method for property <tt>sex</tt>.
	 * 
	 * @param sex value to be assigned to property sex
     */
	public void setSex(String sex) {
		this.sex = sex;
	}

    /**
     * Getter method for property <tt>age</tt>.
     *
     * @return property value of age
     */
	public int getAge() {
		return age;
	}
	
	/**
	 * Setter method for property <tt>age</tt>.
	 * 
	 * @param age value to be assigned to property age
     */
	public void setAge(int age) {
		this.age = age;
	}

    /**
     * Getter method for property <tt>certNo</tt>.
     *
     * @return property value of certNo
     */
	public String getCertNo() {
		return certNo;
	}
	
	/**
	 * Setter method for property <tt>certNo</tt>.
	 * 
	 * @param certNo value to be assigned to property certNo
     */
	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

    /**
     * Getter method for property <tt>birthday</tt>.
     *
     * @return property value of birthday
     */
	public Date getBirthday() {
		return birthday;
	}
	
	/**
	 * Setter method for property <tt>birthday</tt>.
	 * 
	 * @param birthday value to be assigned to property birthday
     */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

    /**
     * Getter method for property <tt>ageGroup</tt>.
     *
     * @return property value of ageGroup
     */
	public String getAgeGroup() {
		return ageGroup;
	}
	
	/**
	 * Setter method for property <tt>ageGroup</tt>.
	 * 
	 * @param ageGroup value to be assigned to property ageGroup
     */
	public void setAgeGroup(String ageGroup) {
		this.ageGroup = ageGroup;
	}

    /**
     * Getter method for property <tt>comName</tt>.
     *
     * @return property value of comName
     */
	public String getComName() {
		return comName;
	}
	
	/**
	 * Setter method for property <tt>comName</tt>.
	 * 
	 * @param comName value to be assigned to property comName
     */
	public void setComName(String comName) {
		this.comName = comName;
	}

    /**
     * Getter method for property <tt>userLevel</tt>.
     *
     * @return property value of userLevel
     */
	public int getUserLevel() {
		return userLevel;
	}
	
	/**
	 * Setter method for property <tt>userLevel</tt>.
	 * 
	 * @param userLevel value to be assigned to property userLevel
     */
	public void setUserLevel(int userLevel) {
		this.userLevel = userLevel;
	}

    /**
     * Getter method for property <tt>recommendUserId</tt>.
     *
     * @return property value of recommendUserId
     */
	public String getRecommendUserId() {
		return recommendUserId;
	}
	
	/**
	 * Setter method for property <tt>recommendUserId</tt>.
	 * 
	 * @param recommendUserId value to be assigned to property recommendUserId
     */
	public void setRecommendUserId(String recommendUserId) {
		this.recommendUserId = recommendUserId;
	}

    /**
     * Getter method for property <tt>recommendUserType</tt>.
     *
     * @return property value of recommendUserType
     */
	public String getRecommendUserType() {
		return recommendUserType;
	}
	
	/**
	 * Setter method for property <tt>recommendUserType</tt>.
	 * 
	 * @param recommendUserType value to be assigned to property recommendUserType
     */
	public void setRecommendUserType(String recommendUserType) {
		this.recommendUserType = recommendUserType;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>isNew</tt>.
     *
     * @return property value of isNew
     */
	public String getIsNew() {
		return isNew;
	}
	
	/**
	 * Setter method for property <tt>isNew</tt>.
	 * 
	 * @param isNew value to be assigned to property isNew
     */
	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

    /**
     * Getter method for property <tt>loginPsw</tt>.
     *
     * @return property value of loginPsw
     */
	public String getLoginPsw() {
		return loginPsw;
	}
	
	/**
	 * Setter method for property <tt>loginPsw</tt>.
	 * 
	 * @param loginPsw value to be assigned to property loginPsw
     */
	public void setLoginPsw(String loginPsw) {
		this.loginPsw = loginPsw;
	}

    /**
     * Getter method for property <tt>canWithdraw</tt>.
     *
     * @return property value of canWithdraw
     */
	public String getCanWithdraw() {
		return canWithdraw;
	}
	
	/**
	 * Setter method for property <tt>canWithdraw</tt>.
	 * 
	 * @param canWithdraw value to be assigned to property canWithdraw
     */
	public void setCanWithdraw(String canWithdraw) {
		this.canWithdraw = canWithdraw;
	}

    /**
     * Getter method for property <tt>realName</tt>.
     *
     * @return property value of realName
     */
	public String getRealName() {
		return realName;
	}
	
	/**
	 * Setter method for property <tt>realName</tt>.
	 * 
	 * @param realName value to be assigned to property realName
     */
	public void setRealName(String realName) {
		this.realName = realName;
	}

    /**
     * Getter method for property <tt>comAddress</tt>.
     *
     * @return property value of comAddress
     */
	public String getComAddress() {
		return comAddress;
	}
	
	/**
	 * Setter method for property <tt>comAddress</tt>.
	 * 
	 * @param comAddress value to be assigned to property comAddress
     */
	public void setComAddress(String comAddress) {
		this.comAddress = comAddress;
	}

    /**
     * Getter method for property <tt>profession</tt>.
     *
     * @return property value of profession
     */
	public String getProfession() {
		return profession;
	}
	
	/**
	 * Setter method for property <tt>profession</tt>.
	 * 
	 * @param profession value to be assigned to property profession
     */
	public void setProfession(String profession) {
		this.profession = profession;
	}

    /**
     * Getter method for property <tt>comfirmMsg</tt>.
     *
     * @return property value of comfirmMsg
     */
	public String getComfirmMsg() {
		return comfirmMsg;
	}
	
	/**
	 * Setter method for property <tt>comfirmMsg</tt>.
	 * 
	 * @param comfirmMsg value to be assigned to property comfirmMsg
     */
	public void setComfirmMsg(String comfirmMsg) {
		this.comfirmMsg = comfirmMsg;
	}

    /**
     * Getter method for property <tt>qrCode</tt>.
     *
     * @return property value of qrCode
     */
	public String getQrCode() {
		return qrCode;
	}
	
	/**
	 * Setter method for property <tt>qrCode</tt>.
	 * 
	 * @param qrCode value to be assigned to property qrCode
     */
	public void setQrCode(String qrCode) {
		this.qrCode = qrCode;
	}

    /**
     * Getter method for property <tt>erpNo</tt>.
     *
     * @return property value of erpNo
     */
	public String getErpNo() {
		return erpNo;
	}
	
	/**
	 * Setter method for property <tt>erpNo</tt>.
	 * 
	 * @param erpNo value to be assigned to property erpNo
     */
	public void setErpNo(String erpNo) {
		this.erpNo = erpNo;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
