/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import com.onway.common.lang.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_withdraw</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_withdraw.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: WithdrawDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class WithdrawDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>WITHDRAW_NO</tt>.
	 */
	private String withdrawNo;

	/**
	 * This property corresponds to db column <tt>ACCOUNT_NO</tt>.
	 */
	private String accountNo;

	/**
	 * This property corresponds to db column <tt>VOUCHER_TYPE</tt>.
	 */
	private String voucherType;

	/**
	 * This property corresponds to db column <tt>VOUCHER_NO</tt>.
	 */
	private String voucherNo;

	/**
	 * This property corresponds to db column <tt>AMOUNT</tt>.
	 */
	private Money amount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>HU_AMOUNT</tt>.
	 */
	private Money huAmount = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>RATE</tt>.
	 */
	private String rate;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>WITHDRAW_FROM</tt>.
	 */
	private String withdrawFrom;

	/**
	 * This property corresponds to db column <tt>WITHDRAW_TYPE</tt>.
	 */
	private String withdrawType;

	/**
	 * This property corresponds to db column <tt>FAIL_REASON</tt>.
	 */
	private String failReason;

	/**
	 * This property corresponds to db column <tt>VOUCEHR_IMG</tt>.
	 */
	private String voucehrImg;

	/**
	 * This property corresponds to db column <tt>GMT_FINISH</tt>.
	 */
	private Date gmtFinish;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>withdrawNo</tt>.
     *
     * @return property value of withdrawNo
     */
	public String getWithdrawNo() {
		return withdrawNo;
	}
	
	/**
	 * Setter method for property <tt>withdrawNo</tt>.
	 * 
	 * @param withdrawNo value to be assigned to property withdrawNo
     */
	public void setWithdrawNo(String withdrawNo) {
		this.withdrawNo = withdrawNo;
	}

    /**
     * Getter method for property <tt>accountNo</tt>.
     *
     * @return property value of accountNo
     */
	public String getAccountNo() {
		return accountNo;
	}
	
	/**
	 * Setter method for property <tt>accountNo</tt>.
	 * 
	 * @param accountNo value to be assigned to property accountNo
     */
	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

    /**
     * Getter method for property <tt>voucherType</tt>.
     *
     * @return property value of voucherType
     */
	public String getVoucherType() {
		return voucherType;
	}
	
	/**
	 * Setter method for property <tt>voucherType</tt>.
	 * 
	 * @param voucherType value to be assigned to property voucherType
     */
	public void setVoucherType(String voucherType) {
		this.voucherType = voucherType;
	}

    /**
     * Getter method for property <tt>voucherNo</tt>.
     *
     * @return property value of voucherNo
     */
	public String getVoucherNo() {
		return voucherNo;
	}
	
	/**
	 * Setter method for property <tt>voucherNo</tt>.
	 * 
	 * @param voucherNo value to be assigned to property voucherNo
     */
	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

    /**
     * Getter method for property <tt>amount</tt>.
     *
     * @return property value of amount
     */
	public Money getAmount() {
		return amount;
	}
	
	/**
	 * Setter method for property <tt>amount</tt>.
	 * 
	 * @param amount value to be assigned to property amount
     */
	public void setAmount(Money amount) {
		if (amount == null) {
			this.amount = new Money(0, 0);
		} else {
			this.amount = amount;
		}
	}

    /**
     * Getter method for property <tt>huAmount</tt>.
     *
     * @return property value of huAmount
     */
	public Money getHuAmount() {
		return huAmount;
	}
	
	/**
	 * Setter method for property <tt>huAmount</tt>.
	 * 
	 * @param huAmount value to be assigned to property huAmount
     */
	public void setHuAmount(Money huAmount) {
		if (huAmount == null) {
			this.huAmount = new Money(0, 0);
		} else {
			this.huAmount = huAmount;
		}
	}

    /**
     * Getter method for property <tt>rate</tt>.
     *
     * @return property value of rate
     */
	public String getRate() {
		return rate;
	}
	
	/**
	 * Setter method for property <tt>rate</tt>.
	 * 
	 * @param rate value to be assigned to property rate
     */
	public void setRate(String rate) {
		this.rate = rate;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>withdrawFrom</tt>.
     *
     * @return property value of withdrawFrom
     */
	public String getWithdrawFrom() {
		return withdrawFrom;
	}
	
	/**
	 * Setter method for property <tt>withdrawFrom</tt>.
	 * 
	 * @param withdrawFrom value to be assigned to property withdrawFrom
     */
	public void setWithdrawFrom(String withdrawFrom) {
		this.withdrawFrom = withdrawFrom;
	}

    /**
     * Getter method for property <tt>withdrawType</tt>.
     *
     * @return property value of withdrawType
     */
	public String getWithdrawType() {
		return withdrawType;
	}
	
	/**
	 * Setter method for property <tt>withdrawType</tt>.
	 * 
	 * @param withdrawType value to be assigned to property withdrawType
     */
	public void setWithdrawType(String withdrawType) {
		this.withdrawType = withdrawType;
	}

    /**
     * Getter method for property <tt>failReason</tt>.
     *
     * @return property value of failReason
     */
	public String getFailReason() {
		return failReason;
	}
	
	/**
	 * Setter method for property <tt>failReason</tt>.
	 * 
	 * @param failReason value to be assigned to property failReason
     */
	public void setFailReason(String failReason) {
		this.failReason = failReason;
	}

    /**
     * Getter method for property <tt>voucehrImg</tt>.
     *
     * @return property value of voucehrImg
     */
	public String getVoucehrImg() {
		return voucehrImg;
	}
	
	/**
	 * Setter method for property <tt>voucehrImg</tt>.
	 * 
	 * @param voucehrImg value to be assigned to property voucehrImg
     */
	public void setVoucehrImg(String voucehrImg) {
		this.voucehrImg = voucehrImg;
	}

    /**
     * Getter method for property <tt>gmtFinish</tt>.
     *
     * @return property value of gmtFinish
     */
	public Date getGmtFinish() {
		return gmtFinish;
	}
	
	/**
	 * Setter method for property <tt>gmtFinish</tt>.
	 * 
	 * @param gmtFinish value to be assigned to property gmtFinish
     */
	public void setGmtFinish(Date gmtFinish) {
		this.gmtFinish = gmtFinish;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
}
