/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>hqyt_word</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_word.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: WordDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class WordDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>WORD_TYPE</tt>.
	 */
	private String wordType;

	/**
	 * This property corresponds to db column <tt>WORD_CONTENT</tt>.
	 */
	private String wordContent;

	/**
	 * This property corresponds to db column <tt>WORD_SUB_TYPE</tt>.
	 */
	private String wordSubType;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>wordType</tt>.
     *
     * @return property value of wordType
     */
	public String getWordType() {
		return wordType;
	}
	
	/**
	 * Setter method for property <tt>wordType</tt>.
	 * 
	 * @param wordType value to be assigned to property wordType
     */
	public void setWordType(String wordType) {
		this.wordType = wordType;
	}

    /**
     * Getter method for property <tt>wordContent</tt>.
     *
     * @return property value of wordContent
     */
	public String getWordContent() {
		return wordContent;
	}
	
	/**
	 * Setter method for property <tt>wordContent</tt>.
	 * 
	 * @param wordContent value to be assigned to property wordContent
     */
	public void setWordContent(String wordContent) {
		this.wordContent = wordContent;
	}

    /**
     * Getter method for property <tt>wordSubType</tt>.
     *
     * @return property value of wordSubType
     */
	public String getWordSubType() {
		return wordSubType;
	}
	
	/**
	 * Setter method for property <tt>wordSubType</tt>.
	 * 
	 * @param wordSubType value to be assigned to property wordSubType
     */
	public void setWordSubType(String wordSubType) {
		this.wordSubType = wordSubType;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
