/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.AccountTempDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.onway.common.lang.Money;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>hqyt_account_temp</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_account_temp.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: AccountTempDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface AccountTempDAO {
	/**
	 *  Query DB table <tt>hqyt_account_temp</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_account_temp</tt>
	 *
	 *	@param linkId
	 *	@param type
	 *	@param temType
	 *	@param delFlg
	 *	@return AccountTempDO
	 *	@throws DataAccessException
	 */	 
    public  AccountTempDO   searchByLinkId(String linkId, String type, String temType, String delFlg) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_account_temp</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_account_temp</tt>
	 *
	 *	@param id
	 *	@return AccountTempDO
	 *	@throws DataAccessException
	 */	 
    public  AccountTempDO   queryById(Integer id) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_account_temp</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_account_temp set AMOUNT=?, END_DATE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((LINK_ID = ?) AND (TYPE = ?) AND (TEMP_TYPE = ?))</tt>
	 *
	 *	@param accountTemp
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updateTemp(AccountTempDO accountTemp) throws DataAccessException;

	/**
	 *  Insert one <tt>AccountTempDO</tt> object to DB table <tt>hqyt_account_temp</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into hqyt_account_temp(LINK_ID,TYPE,TEMP_TYPE,AMOUNT,START_DATE,END_DATE,DEL_FLG,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param accountTemp
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   creatTemp(AccountTempDO accountTemp) throws DataAccessException;

}