/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.GoodsAttrValueDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.HashMap;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>hqyt_goods_attr_value</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_goods_attr_value.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: GoodsAttrValueDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface GoodsAttrValueDAO {
	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, ATTR_ID, VALUE, SORT_NUM, STATUS, MEMO, GMT_CREATE, CREATER, GMT_MODIFIED, MODIFIER from hqyt_goods_attr_value where (ATTR_ID = ?)</tt>
	 *
	 *	@param attrId
	 *	@return List<GoodsAttrValueDO>
	 *	@throws DataAccessException
	 */	 
    public  List<GoodsAttrValueDO>   selectAttrByAttrNo(String attrId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, ATTR_ID, VALUE, SORT_NUM, STATUS, MEMO, GMT_CREATE, CREATER, GMT_MODIFIED, MODIFIER from hqyt_goods_attr_value where ((1 = 1) AND (ATTR_ID = ?) AND (STATUS = ?))</tt>
	 *
	 *	@param attrId
	 *	@param status
	 *	@return List<GoodsAttrValueDO>
	 *	@throws DataAccessException
	 */	 
    public  List<GoodsAttrValueDO>   selectAttrByAttrNoAndSta(String attrId, String status) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from hqyt_goods_attr_value where ((ATTR_ID = ?) AND (VALUE = ?))</tt>
	 *
	 *	@param attrId
	 *	@param value
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public  long   selectCountByAttrNoValue(String attrId, String value) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_goods_attr_value where ((ATTR_ID = ?) AND (VALUE = ?))</tt>
	 *
	 *	@param attrId
	 *	@param value
	 *	@return GoodsAttrValueDO
	 *	@throws DataAccessException
	 */	 
    public  GoodsAttrValueDO   selectByAttrNoValue(String attrId, String value) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, ATTR_ID, VALUE, SORT_NUM, STATUS, MEMO, GMT_CREATE, CREATER, GMT_MODIFIED, MODIFIER from hqyt_goods_attr_value where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return GoodsAttrValueDO
	 *	@throws DataAccessException
	 */	 
    public  GoodsAttrValueDO   selectAttrById(int id) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, ATTR_ID, VALUE, SORT_NUM, STATUS, MEMO, GMT_CREATE, CREATER, GMT_MODIFIED, MODIFIER from hqyt_goods_attr_value where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return HashMap
	 *	@throws DataAccessException
	 */	 
    public  Map<String,Object>  selectById(int id) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_goods_attr_value</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_goods_attr_value set GMT_MODIFIED=CURRENT_TIMESTAMP</tt>
	 *
	 *	@param queryInfo
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   update(GoodsAttrValueDO queryInfo, String userId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>hqyt_goods_attr_value</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from hqyt_goods_attr_value where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   deleteById(int id) throws DataAccessException;

	/**
	 *  Insert one <tt>GoodsAttrValueDO</tt> object to DB table <tt>hqyt_goods_attr_value</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into hqyt_goods_attr_value(ATTR_ID,VALUE,CREATER,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param goodsAttrValue
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insert(GoodsAttrValueDO goodsAttrValue) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_goods_attr_value</tt>
	 *
	 *	@param attrId
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   selectPage(String attrId, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from hqyt_goods_attr_value</tt>
	 *
	 *	@param attrId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   selectPageCount(String attrId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_goods_attr_value</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, ATTR_ID, VALUE, SORT_NUM, STATUS, MEMO, GMT_CREATE, CREATER, GMT_MODIFIED, MODIFIER from hqyt_goods_attr_value where ((VALUE = ?) AND (ATTR_ID = ?))</tt>
	 *
	 *	@param value
	 *	@param attrId
	 *	@return GoodsAttrValueDO
	 *	@throws DataAccessException
	 */	 
    public  GoodsAttrValueDO   selectAttrByValueObj(String value, String attrId) throws DataAccessException;

}