/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.KnowledgeDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>hqyt_knowledge</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_knowledge.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: KnowledgeDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface KnowledgeDAO {
	/**
	 *  Query DB table <tt>hqyt_knowledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_knowledge where (1 = 1)</tt>
	 *
	 *	@param type
	 *	@param title
	 *	@param delFlg
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   selectKnowledge(String type, String title, String delFlg, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Insert one <tt>KnowledgeDO</tt> object to DB table <tt>hqyt_knowledge</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into hqyt_knowledge(KNOW_ID,TYPE,TITLE,SUB_TITLE,CONTENT,HEAD_IMG_URL,PRAISE_COUNT,COMMENT_COUNT,DEL_FLG,GMT_CREATE,GMT_MODIFIED,CREATER,MODIFIER) values (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CREATER, MODIFIER)</tt>
	 *
	 *	@param knowledge
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insertKnowledge(KnowledgeDO knowledge) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_knowledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_knowledge set TYPE=?, TITLE=?, SUB_TITLE=?, CONTENT=?, HEAD_IMG_URL=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (KNOW_ID = ?)</tt>
	 *
	 *	@param type
	 *	@param title
	 *	@param subTitle
	 *	@param content
	 *	@param headImgUrl
	 *	@param modifier
	 *	@param knowId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updateKnowledge(String type, String title, String subTitle, String content, String headImgUrl, String modifier, String knowId) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_knowledge</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_knowledge set DEL_FLG=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (KNOW_ID = ?)</tt>
	 *
	 *	@param delFlg
	 *	@param modifier
	 *	@param knowId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   deleteKnowledge(String delFlg, String modifier, String knowId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_knowledge</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_knowledge</tt>
	 *
	 *	@param type
	 *	@param title
	 *	@param delFlg
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   selectKnowledgeCount(String type, String title, String delFlg) throws DataAccessException;

}