/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import java.util.Date;
import com.onway.fyapp.common.dal.dataobject.MsgDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>hqyt_msg</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_msg.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: MsgDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface MsgDAO {
	/**
	 *  Query DB table <tt>hqyt_msg</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_msg</tt>
	 *
	 *	@param userId
	 *	@param msgType
	 *	@param msgTitle
	 *	@param isRead
	 *	@param startDate
	 *	@param endDate
	 *	@param userCell
	 *	@param userNickName
	 *	@param userRealName
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   selectMsg(String userId, String msgType, String msgTitle, String isRead, Date startDate, Date endDate, String userCell, String userNickName, String userRealName, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_msg</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_msg</tt>
	 *
	 *	@param userId
	 *	@param msgType
	 *	@param msgTitle
	 *	@param isRead
	 *	@param startDate
	 *	@param endDate
	 *	@param userCell
	 *	@param userNickName
	 *	@param userRealName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   selectMsgCount(String userId, String msgType, String msgTitle, String isRead, Date startDate, Date endDate, String userCell, String userNickName, String userRealName) throws DataAccessException;

	/**
	 *  Insert one <tt>MsgDO</tt> object to DB table <tt>hqyt_msg</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into hqyt_msg(USER_ID,MSG_TYPE,MSG_TITLE,MSG_CONTENT,IS_READ,CREATER,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param msg
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insertMsg(MsgDO msg) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_msg</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_msg set USER_ID=?, MSG_TYPE=?, MSG_TITLE=?, MSG_CONTENT=?, MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ID = ?)</tt>
	 *
	 *	@param userId
	 *	@param msgType
	 *	@param msgTitle
	 *	@param msgContent
	 *	@param modifier
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updateMsg(String userId, String msgType, String msgTitle, String msgContent, String modifier, int id) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_msg</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_msg set IS_DEL='1', MODIFIER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ID = ?)</tt>
	 *
	 *	@param modifier
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   deleteMsg(String modifier, int id) throws DataAccessException;

}