/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.OrderReturnDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Date;
import java.math.BigDecimal;
import com.onway.common.lang.Money;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>hqyt_order_return</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_order_return.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: OrderReturnDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface OrderReturnDAO {
	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_order_return where (CHILD_ORDER_ID = ?)</tt>
	 *
	 *	@param childOrderId
	 *	@return OrderReturnDO
	 *	@throws DataAccessException
	 */	 
    public  OrderReturnDO   selectByChildOrderId(String childOrderId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_order_return</tt>
	 *
	 *	@param childOrderId
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   getOrderReturnRecord(String childOrderId, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_order_return</tt>
	 *
	 *	@param childOrderId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   getOrderReturnRecordCount(String childOrderId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_order_return</tt>
	 *
	 *	@param reasonMain
	 *	@param teamIds
	 *	@param operMsg
	 *	@param userMsg
	 *	@param proMsg
	 *	@param conStatus
	 *	@param startDate
	 *	@param endDate
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   getOrderComplainRecord(String reasonMain, List teamIds, String operMsg, String userMsg, String proMsg, List conStatus, Date startDate, Date endDate, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from hqyt_order_return</tt>
	 *
	 *	@param reasonMain
	 *	@param teamIds
	 *	@param operMsg
	 *	@param userMsg
	 *	@param proMsg
	 *	@param conStatus
	 *	@param startDate
	 *	@param endDate
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   getOrderComplainRecordCount(String reasonMain, List teamIds, String operMsg, String userMsg, String proMsg, List conStatus, Date startDate, Date endDate) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select SUM(SHOULD_RETURN_MONEY) from hqyt_order_return</tt>
	 *
	 *	@param childOrderId
	 *	@param status
	 *	@return BigDecimal
	 *	@throws DataAccessException
	 */	 
    public  BigDecimal   sumAmountOrderReturnSucc(String childOrderId, String status) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_order_return</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select SUM(SHOULD_RETURN_MONEY) from hqyt_order_return</tt>
	 *
	 *	@param childOrderIds
	 *	@param status
	 *	@return BigDecimal
	 *	@throws DataAccessException
	 */	 
    public  BigDecimal   sumAmountOrderReturnSuccIds(List childOrderIds, String status) throws DataAccessException;

}