/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.SysConfigDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>sys_config</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: SysConfigDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface SysConfigDAO {
	/**
	 *  Query DB table <tt>sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sys_key, sys_value, status, memo, gmt_create, gmt_modified from sys_config</tt>
	 *
	 *	@return List<SysConfigDO>
	 *	@throws DataAccessException
	 */	 
    public  List<SysConfigDO>   loadAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from sys_config</tt>
	 *
	 *	@param memo
	 *	@param offset
	 *	@param limit
	 *	@return List<SysConfigDO>
	 *	@throws DataAccessException
	 */	 
    public  List<SysConfigDO>   selectallsysconfig(String memo, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from sys_config</tt>
	 *
	 *	@param memo
	 *	@return List<Long>
	 *	@throws DataAccessException
	 */	 
    public  List<Long>   selectallsysconfigcount(String memo) throws DataAccessException;

	/**
	 *  Update DB table <tt>sys_config</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sys_config set id=id</tt>
	 *
	 *	@param gmtmodified
	 *	@param key
	 *	@param value
	 *	@param status
	 *	@param memo
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updatesysconfig(Date gmtmodified, String key, String value, String status, String memo, String id) throws DataAccessException;

	/**
	 *  Insert one <tt>SysConfigDO</tt> object to DB table <tt>sys_config</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sys_config(SYS_KEY,SYS_VALUE,STATUS,MEMO,GMT_CREATE) values (?, ?, ?, ?, ?)</tt>
	 *
	 *	@param sysConfig
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insertsysconfig(SysConfigDO sysConfig) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, SYS_KEY, SYS_VALUE, STATUS, MEMO, GMT_CREATE, GMT_MODIFIED from sys_config where (SYS_KEY = ?)</tt>
	 *
	 *	@param sysKey
	 *	@return SysConfigDO
	 *	@throws DataAccessException
	 */	 
    public  SysConfigDO   selectSysConfigBySysKey(String sysKey) throws DataAccessException;

}