/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.TeamUserDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>hqyt_team_user</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/hqyt_team_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: TeamUserDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface TeamUserDAO {
	/**
	 *  Insert one <tt>TeamUserDO</tt> object to DB table <tt>hqyt_team_user</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into hqyt_team_user(TEAM_ID,TEAM_USER_ID,TEAM_LEDER,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param teamUser
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insertteamuser(TeamUserDO teamUser) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_team_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, TEAM_ID, TEAM_USER_ID, TEAM_LEDER, GMT_CREATE, GMT_MODIFIED from hqyt_team_user where ((TEAM_ID = ?) AND (TEAM_LEDER = ?))</tt>
	 *
	 *	@param teamId
	 *	@param teamLeder
	 *	@return TeamUserDO
	 *	@throws DataAccessException
	 */	 
    public  TeamUserDO   selectLeaderByTeamId(String teamId, String teamLeder) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>hqyt_team_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from hqyt_team_user where (TEAM_USER_ID = ?)</tt>
	 *
	 *	@param teamUserId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   deleteteamuser(String teamUserId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_team_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_team_user where ((TEAM_ID = ?) AND (TEAM_LEDER = ?))</tt>
	 *
	 *	@param teamId
	 *	@param teamLeder
	 *	@return TeamUserDO
	 *	@throws DataAccessException
	 */	 
    public  TeamUserDO   checkld(String teamId, String teamLeder) throws DataAccessException;

	/**
	 *  Update DB table <tt>hqyt_team_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update hqyt_team_user set TEAM_LEDER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (TEAM_USER_ID = ?)</tt>
	 *
	 *	@param teamLeder
	 *	@param teamUserId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   changeTeamRole(String teamLeder, String teamUserId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_team_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, TEAM_ID, TEAM_USER_ID, TEAM_LEDER, GMT_CREATE, GMT_MODIFIED from hqyt_team_user where (TEAM_USER_ID = ?)</tt>
	 *
	 *	@param teamUserId
	 *	@return TeamUserDO
	 *	@throws DataAccessException
	 */	 
    public  TeamUserDO   getUserTeamInfo(String teamUserId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_team_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_team_user where ((TEAM_ID = ?) AND (TEAM_USER_ID = ?))</tt>
	 *
	 *	@param teamId
	 *	@param teamUserId
	 *	@return TeamUserDO
	 *	@throws DataAccessException
	 */	 
    public  TeamUserDO   checkOnlyUserTeam(String teamId, String teamUserId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>hqyt_team_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from hqyt_team_user where (TEAM_ID = ?)</tt>
	 *
	 *	@param teamId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   cleanALlTeamLink(String teamId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_team_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_team_user</tt>
	 *
	 *	@param userId
	 *	@return TeamUserDO
	 *	@throws DataAccessException
	 */	 
    public  TeamUserDO   searchMyTeam(String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>hqyt_team_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from hqyt_team_user</tt>
	 *
	 *	@param teamId
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 
    public  List<String>   searchAllUserId(String teamId) throws DataAccessException;

}